version: "2"
output:
  formats:
    text:
      path: stdout
      colors: false
linters:
  enable:
    - copyloopvar
    - errorlint
    - exhaustive
    - gocritic
    - whitespace
    - wsl_v5
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gocritic:
      enabled-checks:
        - rangeValCopy
        - boolExprSimplify
        - emptyFallthrough
        - emptyStringTest
        - nestingReduce
        - paramTypeCombine
        - stringXbytes
        - typeAssertChain
        - typeUnparen
        - unlabelStmt
        - unnecessaryBlock
        - yodaStyleExpr
        - appendCombine
        - equalFold
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: true
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/piraeusdatastore/linstor-csi)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
