apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor-basic-storage
provisioner: linstor.csi.linbit.com
parameters:
  placementCount: "2"
  storagePool: "my-storage-pool"
  resourceGroup: "linstor-basic-storage"
