---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: linstor-csi-node
spec:
  template:
    spec:
      initContainers:
      - name: linstor-wait-node-online
        env:
        - name: LS_CONTROLLERS
          value: LINSTOR_CONTROLLER_URL
      containers:
      - name: linstor-csi
        env:
        - name: LS_CONTROLLERS
          value: LINSTOR_CONTROLLER_URL
