// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LINBIT/golinstor/client"
	mock "github.com/stretchr/testify/mock"
)

// NewEncryptionProvider creates a new instance of EncryptionProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEncryptionProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *EncryptionProvider {
	mock := &EncryptionProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EncryptionProvider is an autogenerated mock type for the EncryptionProvider type
type EncryptionProvider struct {
	mock.Mock
}

type EncryptionProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *EncryptionProvider) EXPECT() *EncryptionProvider_Expecter {
	return &EncryptionProvider_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type EncryptionProvider
func (_mock *EncryptionProvider) Create(ctx context.Context, passphrase client.Passphrase) error {
	ret := _mock.Called(ctx, passphrase)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.Passphrase) error); ok {
		r0 = returnFunc(ctx, passphrase)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EncryptionProvider_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type EncryptionProvider_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - passphrase client.Passphrase
func (_e *EncryptionProvider_Expecter) Create(ctx any, passphrase any) *EncryptionProvider_Create_Call {
	return &EncryptionProvider_Create_Call{Call: _e.mock.On("Create", ctx, passphrase)}
}

func (_c *EncryptionProvider_Create_Call) Run(run func(ctx context.Context, passphrase client.Passphrase)) *EncryptionProvider_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.Passphrase
		if args[1] != nil {
			arg1 = args[1].(client.Passphrase)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EncryptionProvider_Create_Call) Return(err error) *EncryptionProvider_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EncryptionProvider_Create_Call) RunAndReturn(run func(ctx context.Context, passphrase client.Passphrase) error) *EncryptionProvider_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Enter provides a mock function for the type EncryptionProvider
func (_mock *EncryptionProvider) Enter(ctx context.Context, password string) error {
	ret := _mock.Called(ctx, password)

	if len(ret) == 0 {
		panic("no return value specified for Enter")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EncryptionProvider_Enter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enter'
type EncryptionProvider_Enter_Call struct {
	*mock.Call
}

// Enter is a helper method to define mock.On call
//   - ctx context.Context
//   - password string
func (_e *EncryptionProvider_Expecter) Enter(ctx any, password any) *EncryptionProvider_Enter_Call {
	return &EncryptionProvider_Enter_Call{Call: _e.mock.On("Enter", ctx, password)}
}

func (_c *EncryptionProvider_Enter_Call) Run(run func(ctx context.Context, password string)) *EncryptionProvider_Enter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EncryptionProvider_Enter_Call) Return(err error) *EncryptionProvider_Enter_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EncryptionProvider_Enter_Call) RunAndReturn(run func(ctx context.Context, password string) error) *EncryptionProvider_Enter_Call {
	_c.Call.Return(run)
	return _c
}

// Modify provides a mock function for the type EncryptionProvider
func (_mock *EncryptionProvider) Modify(ctx context.Context, passphrase client.Passphrase) error {
	ret := _mock.Called(ctx, passphrase)

	if len(ret) == 0 {
		panic("no return value specified for Modify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.Passphrase) error); ok {
		r0 = returnFunc(ctx, passphrase)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EncryptionProvider_Modify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modify'
type EncryptionProvider_Modify_Call struct {
	*mock.Call
}

// Modify is a helper method to define mock.On call
//   - ctx context.Context
//   - passphrase client.Passphrase
func (_e *EncryptionProvider_Expecter) Modify(ctx any, passphrase any) *EncryptionProvider_Modify_Call {
	return &EncryptionProvider_Modify_Call{Call: _e.mock.On("Modify", ctx, passphrase)}
}

func (_c *EncryptionProvider_Modify_Call) Run(run func(ctx context.Context, passphrase client.Passphrase)) *EncryptionProvider_Modify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.Passphrase
		if args[1] != nil {
			arg1 = args[1].(client.Passphrase)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EncryptionProvider_Modify_Call) Return(err error) *EncryptionProvider_Modify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EncryptionProvider_Modify_Call) RunAndReturn(run func(ctx context.Context, passphrase client.Passphrase) error) *EncryptionProvider_Modify_Call {
	_c.Call.Return(run)
	return _c
}
