// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LINBIT/golinstor/client"
	mock "github.com/stretchr/testify/mock"
)

// NewKeyValueStoreProvider creates a new instance of KeyValueStoreProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeyValueStoreProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeyValueStoreProvider {
	mock := &KeyValueStoreProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// KeyValueStoreProvider is an autogenerated mock type for the KeyValueStoreProvider type
type KeyValueStoreProvider struct {
	mock.Mock
}

type KeyValueStoreProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *KeyValueStoreProvider) EXPECT() *KeyValueStoreProvider_Expecter {
	return &KeyValueStoreProvider_Expecter{mock: &_m.Mock}
}

// CreateOrModify provides a mock function for the type KeyValueStoreProvider
func (_mock *KeyValueStoreProvider) CreateOrModify(ctx context.Context, kv string, modify client.GenericPropsModify) error {
	ret := _mock.Called(ctx, kv, modify)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrModify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.GenericPropsModify) error); ok {
		r0 = returnFunc(ctx, kv, modify)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// KeyValueStoreProvider_CreateOrModify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrModify'
type KeyValueStoreProvider_CreateOrModify_Call struct {
	*mock.Call
}

// CreateOrModify is a helper method to define mock.On call
//   - ctx context.Context
//   - kv string
//   - modify client.GenericPropsModify
func (_e *KeyValueStoreProvider_Expecter) CreateOrModify(ctx any, kv any, modify any) *KeyValueStoreProvider_CreateOrModify_Call {
	return &KeyValueStoreProvider_CreateOrModify_Call{Call: _e.mock.On("CreateOrModify", ctx, kv, modify)}
}

func (_c *KeyValueStoreProvider_CreateOrModify_Call) Run(run func(ctx context.Context, kv string, modify client.GenericPropsModify)) *KeyValueStoreProvider_CreateOrModify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.GenericPropsModify
		if args[2] != nil {
			arg2 = args[2].(client.GenericPropsModify)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *KeyValueStoreProvider_CreateOrModify_Call) Return(err error) *KeyValueStoreProvider_CreateOrModify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *KeyValueStoreProvider_CreateOrModify_Call) RunAndReturn(run func(ctx context.Context, kv string, modify client.GenericPropsModify) error) *KeyValueStoreProvider_CreateOrModify_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type KeyValueStoreProvider
func (_mock *KeyValueStoreProvider) Delete(ctx context.Context, kv string) error {
	ret := _mock.Called(ctx, kv)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, kv)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// KeyValueStoreProvider_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type KeyValueStoreProvider_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - kv string
func (_e *KeyValueStoreProvider_Expecter) Delete(ctx any, kv any) *KeyValueStoreProvider_Delete_Call {
	return &KeyValueStoreProvider_Delete_Call{Call: _e.mock.On("Delete", ctx, kv)}
}

func (_c *KeyValueStoreProvider_Delete_Call) Run(run func(ctx context.Context, kv string)) *KeyValueStoreProvider_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KeyValueStoreProvider_Delete_Call) Return(err error) *KeyValueStoreProvider_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *KeyValueStoreProvider_Delete_Call) RunAndReturn(run func(ctx context.Context, kv string) error) *KeyValueStoreProvider_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type KeyValueStoreProvider
func (_mock *KeyValueStoreProvider) Get(ctx context.Context, kv string) (*client.KV, error) {
	ret := _mock.Called(ctx, kv)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *client.KV
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*client.KV, error)); ok {
		return returnFunc(ctx, kv)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *client.KV); ok {
		r0 = returnFunc(ctx, kv)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.KV)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, kv)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KeyValueStoreProvider_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type KeyValueStoreProvider_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - kv string
func (_e *KeyValueStoreProvider_Expecter) Get(ctx any, kv any) *KeyValueStoreProvider_Get_Call {
	return &KeyValueStoreProvider_Get_Call{Call: _e.mock.On("Get", ctx, kv)}
}

func (_c *KeyValueStoreProvider_Get_Call) Run(run func(ctx context.Context, kv string)) *KeyValueStoreProvider_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KeyValueStoreProvider_Get_Call) Return(kV *client.KV, err error) *KeyValueStoreProvider_Get_Call {
	_c.Call.Return(kV, err)
	return _c
}

func (_c *KeyValueStoreProvider_Get_Call) RunAndReturn(run func(ctx context.Context, kv string) (*client.KV, error)) *KeyValueStoreProvider_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type KeyValueStoreProvider
func (_mock *KeyValueStoreProvider) List(ctx context.Context) ([]client.KV, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []client.KV
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]client.KV, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []client.KV); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.KV)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KeyValueStoreProvider_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type KeyValueStoreProvider_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *KeyValueStoreProvider_Expecter) List(ctx any) *KeyValueStoreProvider_List_Call {
	return &KeyValueStoreProvider_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *KeyValueStoreProvider_List_Call) Run(run func(ctx context.Context)) *KeyValueStoreProvider_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *KeyValueStoreProvider_List_Call) Return(kVs []client.KV, err error) *KeyValueStoreProvider_List_Call {
	_c.Call.Return(kVs, err)
	return _c
}

func (_c *KeyValueStoreProvider_List_Call) RunAndReturn(run func(ctx context.Context) ([]client.KV, error)) *KeyValueStoreProvider_List_Call {
	_c.Call.Return(run)
	return _c
}
