// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewLeveledLogger creates a new instance of LeveledLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLeveledLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *LeveledLogger {
	mock := &LeveledLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LeveledLogger is an autogenerated mock type for the LeveledLogger type
type LeveledLogger struct {
	mock.Mock
}

type LeveledLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *LeveledLogger) EXPECT() *LeveledLogger_Expecter {
	return &LeveledLogger_Expecter{mock: &_m.Mock}
}

// Debugf provides a mock function for the type LeveledLogger
func (_mock *LeveledLogger) Debugf(s string, ifaceVals ...interface{}) {
	if len(ifaceVals) > 0 {
		_mock.Called(s, ifaceVals)
	} else {
		_mock.Called(s)
	}

	return
}

// LeveledLogger_Debugf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debugf'
type LeveledLogger_Debugf_Call struct {
	*mock.Call
}

// Debugf is a helper method to define mock.On call
//   - s string
//   - ifaceVals ...interface{}
func (_e *LeveledLogger_Expecter) Debugf(s any, ifaceVals ...any) *LeveledLogger_Debugf_Call {
	return &LeveledLogger_Debugf_Call{Call: _e.mock.On("Debugf",
		append([]any{s}, ifaceVals...)...)}
}

func (_c *LeveledLogger_Debugf_Call) Run(run func(s string, ifaceVals ...interface{})) *LeveledLogger_Debugf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *LeveledLogger_Debugf_Call) Return() *LeveledLogger_Debugf_Call {
	_c.Call.Return()
	return _c
}

func (_c *LeveledLogger_Debugf_Call) RunAndReturn(run func(s string, ifaceVals ...interface{})) *LeveledLogger_Debugf_Call {
	_c.Run(run)
	return _c
}

// Errorf provides a mock function for the type LeveledLogger
func (_mock *LeveledLogger) Errorf(s string, ifaceVals ...interface{}) {
	if len(ifaceVals) > 0 {
		_mock.Called(s, ifaceVals)
	} else {
		_mock.Called(s)
	}

	return
}

// LeveledLogger_Errorf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errorf'
type LeveledLogger_Errorf_Call struct {
	*mock.Call
}

// Errorf is a helper method to define mock.On call
//   - s string
//   - ifaceVals ...interface{}
func (_e *LeveledLogger_Expecter) Errorf(s any, ifaceVals ...any) *LeveledLogger_Errorf_Call {
	return &LeveledLogger_Errorf_Call{Call: _e.mock.On("Errorf",
		append([]any{s}, ifaceVals...)...)}
}

func (_c *LeveledLogger_Errorf_Call) Run(run func(s string, ifaceVals ...interface{})) *LeveledLogger_Errorf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *LeveledLogger_Errorf_Call) Return() *LeveledLogger_Errorf_Call {
	_c.Call.Return()
	return _c
}

func (_c *LeveledLogger_Errorf_Call) RunAndReturn(run func(s string, ifaceVals ...interface{})) *LeveledLogger_Errorf_Call {
	_c.Run(run)
	return _c
}

// Infof provides a mock function for the type LeveledLogger
func (_mock *LeveledLogger) Infof(s string, ifaceVals ...interface{}) {
	if len(ifaceVals) > 0 {
		_mock.Called(s, ifaceVals)
	} else {
		_mock.Called(s)
	}

	return
}

// LeveledLogger_Infof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Infof'
type LeveledLogger_Infof_Call struct {
	*mock.Call
}

// Infof is a helper method to define mock.On call
//   - s string
//   - ifaceVals ...interface{}
func (_e *LeveledLogger_Expecter) Infof(s any, ifaceVals ...any) *LeveledLogger_Infof_Call {
	return &LeveledLogger_Infof_Call{Call: _e.mock.On("Infof",
		append([]any{s}, ifaceVals...)...)}
}

func (_c *LeveledLogger_Infof_Call) Run(run func(s string, ifaceVals ...interface{})) *LeveledLogger_Infof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *LeveledLogger_Infof_Call) Return() *LeveledLogger_Infof_Call {
	_c.Call.Return()
	return _c
}

func (_c *LeveledLogger_Infof_Call) RunAndReturn(run func(s string, ifaceVals ...interface{})) *LeveledLogger_Infof_Call {
	_c.Run(run)
	return _c
}

// Warnf provides a mock function for the type LeveledLogger
func (_mock *LeveledLogger) Warnf(s string, ifaceVals ...interface{}) {
	if len(ifaceVals) > 0 {
		_mock.Called(s, ifaceVals)
	} else {
		_mock.Called(s)
	}

	return
}

// LeveledLogger_Warnf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warnf'
type LeveledLogger_Warnf_Call struct {
	*mock.Call
}

// Warnf is a helper method to define mock.On call
//   - s string
//   - ifaceVals ...interface{}
func (_e *LeveledLogger_Expecter) Warnf(s any, ifaceVals ...any) *LeveledLogger_Warnf_Call {
	return &LeveledLogger_Warnf_Call{Call: _e.mock.On("Warnf",
		append([]any{s}, ifaceVals...)...)}
}

func (_c *LeveledLogger_Warnf_Call) Run(run func(s string, ifaceVals ...interface{})) *LeveledLogger_Warnf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *LeveledLogger_Warnf_Call) Return() *LeveledLogger_Warnf_Call {
	_c.Call.Return()
	return _c
}

func (_c *LeveledLogger_Warnf_Call) RunAndReturn(run func(s string, ifaceVals ...interface{})) *LeveledLogger_Warnf_Call {
	_c.Run(run)
	return _c
}
