// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// OneOfDrbdResourceDefinitionLayerOpenflexResourceDefinitionLayer is an autogenerated mock type for the OneOfDrbdResourceDefinitionLayerOpenflexResourceDefinitionLayer type
type OneOfDrbdResourceDefinitionLayerOpenflexResourceDefinitionLayer struct {
	mock.Mock
}

// isOneOfDrbdResourceDefinitionLayerOpenflexResourceDefinitionLayer provides a mock function with given fields:
func (_m *OneOfDrbdResourceDefinitionLayerOpenflexResourceDefinitionLayer) isOneOfDrbdResourceDefinitionLayerOpenflexResourceDefinitionLayer() {
	_m.Called()
}
