// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LINBIT/golinstor/client"
	mock "github.com/stretchr/testify/mock"
)

// NewRemoteProvider creates a new instance of RemoteProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRemoteProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *RemoteProvider {
	mock := &RemoteProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RemoteProvider is an autogenerated mock type for the RemoteProvider type
type RemoteProvider struct {
	mock.Mock
}

type RemoteProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *RemoteProvider) EXPECT() *RemoteProvider_Expecter {
	return &RemoteProvider_Expecter{mock: &_m.Mock}
}

// CreateEbs provides a mock function for the type RemoteProvider
func (_mock *RemoteProvider) CreateEbs(ctx context.Context, create client.EbsRemote) error {
	ret := _mock.Called(ctx, create)

	if len(ret) == 0 {
		panic("no return value specified for CreateEbs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.EbsRemote) error); ok {
		r0 = returnFunc(ctx, create)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RemoteProvider_CreateEbs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEbs'
type RemoteProvider_CreateEbs_Call struct {
	*mock.Call
}

// CreateEbs is a helper method to define mock.On call
//   - ctx context.Context
//   - create client.EbsRemote
func (_e *RemoteProvider_Expecter) CreateEbs(ctx any, create any) *RemoteProvider_CreateEbs_Call {
	return &RemoteProvider_CreateEbs_Call{Call: _e.mock.On("CreateEbs", ctx, create)}
}

func (_c *RemoteProvider_CreateEbs_Call) Run(run func(ctx context.Context, create client.EbsRemote)) *RemoteProvider_CreateEbs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.EbsRemote
		if args[1] != nil {
			arg1 = args[1].(client.EbsRemote)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RemoteProvider_CreateEbs_Call) Return(err error) *RemoteProvider_CreateEbs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RemoteProvider_CreateEbs_Call) RunAndReturn(run func(ctx context.Context, create client.EbsRemote) error) *RemoteProvider_CreateEbs_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLinstor provides a mock function for the type RemoteProvider
func (_mock *RemoteProvider) CreateLinstor(ctx context.Context, create client.LinstorRemote) error {
	ret := _mock.Called(ctx, create)

	if len(ret) == 0 {
		panic("no return value specified for CreateLinstor")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.LinstorRemote) error); ok {
		r0 = returnFunc(ctx, create)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RemoteProvider_CreateLinstor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLinstor'
type RemoteProvider_CreateLinstor_Call struct {
	*mock.Call
}

// CreateLinstor is a helper method to define mock.On call
//   - ctx context.Context
//   - create client.LinstorRemote
func (_e *RemoteProvider_Expecter) CreateLinstor(ctx any, create any) *RemoteProvider_CreateLinstor_Call {
	return &RemoteProvider_CreateLinstor_Call{Call: _e.mock.On("CreateLinstor", ctx, create)}
}

func (_c *RemoteProvider_CreateLinstor_Call) Run(run func(ctx context.Context, create client.LinstorRemote)) *RemoteProvider_CreateLinstor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.LinstorRemote
		if args[1] != nil {
			arg1 = args[1].(client.LinstorRemote)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RemoteProvider_CreateLinstor_Call) Return(err error) *RemoteProvider_CreateLinstor_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RemoteProvider_CreateLinstor_Call) RunAndReturn(run func(ctx context.Context, create client.LinstorRemote) error) *RemoteProvider_CreateLinstor_Call {
	_c.Call.Return(run)
	return _c
}

// CreateS3 provides a mock function for the type RemoteProvider
func (_mock *RemoteProvider) CreateS3(ctx context.Context, create client.S3Remote) error {
	ret := _mock.Called(ctx, create)

	if len(ret) == 0 {
		panic("no return value specified for CreateS3")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.S3Remote) error); ok {
		r0 = returnFunc(ctx, create)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RemoteProvider_CreateS3_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateS3'
type RemoteProvider_CreateS3_Call struct {
	*mock.Call
}

// CreateS3 is a helper method to define mock.On call
//   - ctx context.Context
//   - create client.S3Remote
func (_e *RemoteProvider_Expecter) CreateS3(ctx any, create any) *RemoteProvider_CreateS3_Call {
	return &RemoteProvider_CreateS3_Call{Call: _e.mock.On("CreateS3", ctx, create)}
}

func (_c *RemoteProvider_CreateS3_Call) Run(run func(ctx context.Context, create client.S3Remote)) *RemoteProvider_CreateS3_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.S3Remote
		if args[1] != nil {
			arg1 = args[1].(client.S3Remote)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RemoteProvider_CreateS3_Call) Return(err error) *RemoteProvider_CreateS3_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RemoteProvider_CreateS3_Call) RunAndReturn(run func(ctx context.Context, create client.S3Remote) error) *RemoteProvider_CreateS3_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type RemoteProvider
func (_mock *RemoteProvider) Delete(ctx context.Context, remoteName string) error {
	ret := _mock.Called(ctx, remoteName)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, remoteName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RemoteProvider_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type RemoteProvider_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - remoteName string
func (_e *RemoteProvider_Expecter) Delete(ctx any, remoteName any) *RemoteProvider_Delete_Call {
	return &RemoteProvider_Delete_Call{Call: _e.mock.On("Delete", ctx, remoteName)}
}

func (_c *RemoteProvider_Delete_Call) Run(run func(ctx context.Context, remoteName string)) *RemoteProvider_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RemoteProvider_Delete_Call) Return(err error) *RemoteProvider_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RemoteProvider_Delete_Call) RunAndReturn(run func(ctx context.Context, remoteName string) error) *RemoteProvider_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type RemoteProvider
func (_mock *RemoteProvider) GetAll(ctx context.Context, opts ...*client.ListOpts) (client.RemoteList, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 client.RemoteList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*client.ListOpts) (client.RemoteList, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*client.ListOpts) client.RemoteList); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		r0 = ret.Get(0).(client.RemoteList)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...*client.ListOpts) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RemoteProvider_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type RemoteProvider_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...*client.ListOpts
func (_e *RemoteProvider_Expecter) GetAll(ctx any, opts ...any) *RemoteProvider_GetAll_Call {
	return &RemoteProvider_GetAll_Call{Call: _e.mock.On("GetAll",
		append([]any{ctx}, opts...)...)}
}

func (_c *RemoteProvider_GetAll_Call) Run(run func(ctx context.Context, opts ...*client.ListOpts)) *RemoteProvider_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*client.ListOpts
		var variadicArgs []*client.ListOpts
		if len(args) > 1 {
			variadicArgs = args[1].([]*client.ListOpts)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *RemoteProvider_GetAll_Call) Return(remoteList client.RemoteList, err error) *RemoteProvider_GetAll_Call {
	_c.Call.Return(remoteList, err)
	return _c
}

func (_c *RemoteProvider_GetAll_Call) RunAndReturn(run func(ctx context.Context, opts ...*client.ListOpts) (client.RemoteList, error)) *RemoteProvider_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllEbs provides a mock function for the type RemoteProvider
func (_mock *RemoteProvider) GetAllEbs(ctx context.Context, opts ...*client.ListOpts) ([]client.EbsRemote, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAllEbs")
	}

	var r0 []client.EbsRemote
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*client.ListOpts) ([]client.EbsRemote, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*client.ListOpts) []client.EbsRemote); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.EbsRemote)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...*client.ListOpts) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RemoteProvider_GetAllEbs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllEbs'
type RemoteProvider_GetAllEbs_Call struct {
	*mock.Call
}

// GetAllEbs is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...*client.ListOpts
func (_e *RemoteProvider_Expecter) GetAllEbs(ctx any, opts ...any) *RemoteProvider_GetAllEbs_Call {
	return &RemoteProvider_GetAllEbs_Call{Call: _e.mock.On("GetAllEbs",
		append([]any{ctx}, opts...)...)}
}

func (_c *RemoteProvider_GetAllEbs_Call) Run(run func(ctx context.Context, opts ...*client.ListOpts)) *RemoteProvider_GetAllEbs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*client.ListOpts
		var variadicArgs []*client.ListOpts
		if len(args) > 1 {
			variadicArgs = args[1].([]*client.ListOpts)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *RemoteProvider_GetAllEbs_Call) Return(ebsRemotes []client.EbsRemote, err error) *RemoteProvider_GetAllEbs_Call {
	_c.Call.Return(ebsRemotes, err)
	return _c
}

func (_c *RemoteProvider_GetAllEbs_Call) RunAndReturn(run func(ctx context.Context, opts ...*client.ListOpts) ([]client.EbsRemote, error)) *RemoteProvider_GetAllEbs_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllLinstor provides a mock function for the type RemoteProvider
func (_mock *RemoteProvider) GetAllLinstor(ctx context.Context, opts ...*client.ListOpts) ([]client.LinstorRemote, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAllLinstor")
	}

	var r0 []client.LinstorRemote
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*client.ListOpts) ([]client.LinstorRemote, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*client.ListOpts) []client.LinstorRemote); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.LinstorRemote)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...*client.ListOpts) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RemoteProvider_GetAllLinstor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllLinstor'
type RemoteProvider_GetAllLinstor_Call struct {
	*mock.Call
}

// GetAllLinstor is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...*client.ListOpts
func (_e *RemoteProvider_Expecter) GetAllLinstor(ctx any, opts ...any) *RemoteProvider_GetAllLinstor_Call {
	return &RemoteProvider_GetAllLinstor_Call{Call: _e.mock.On("GetAllLinstor",
		append([]any{ctx}, opts...)...)}
}

func (_c *RemoteProvider_GetAllLinstor_Call) Run(run func(ctx context.Context, opts ...*client.ListOpts)) *RemoteProvider_GetAllLinstor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*client.ListOpts
		var variadicArgs []*client.ListOpts
		if len(args) > 1 {
			variadicArgs = args[1].([]*client.ListOpts)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *RemoteProvider_GetAllLinstor_Call) Return(linstorRemotes []client.LinstorRemote, err error) *RemoteProvider_GetAllLinstor_Call {
	_c.Call.Return(linstorRemotes, err)
	return _c
}

func (_c *RemoteProvider_GetAllLinstor_Call) RunAndReturn(run func(ctx context.Context, opts ...*client.ListOpts) ([]client.LinstorRemote, error)) *RemoteProvider_GetAllLinstor_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllS3 provides a mock function for the type RemoteProvider
func (_mock *RemoteProvider) GetAllS3(ctx context.Context, opts ...*client.ListOpts) ([]client.S3Remote, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAllS3")
	}

	var r0 []client.S3Remote
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*client.ListOpts) ([]client.S3Remote, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*client.ListOpts) []client.S3Remote); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.S3Remote)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...*client.ListOpts) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RemoteProvider_GetAllS3_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllS3'
type RemoteProvider_GetAllS3_Call struct {
	*mock.Call
}

// GetAllS3 is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...*client.ListOpts
func (_e *RemoteProvider_Expecter) GetAllS3(ctx any, opts ...any) *RemoteProvider_GetAllS3_Call {
	return &RemoteProvider_GetAllS3_Call{Call: _e.mock.On("GetAllS3",
		append([]any{ctx}, opts...)...)}
}

func (_c *RemoteProvider_GetAllS3_Call) Run(run func(ctx context.Context, opts ...*client.ListOpts)) *RemoteProvider_GetAllS3_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*client.ListOpts
		var variadicArgs []*client.ListOpts
		if len(args) > 1 {
			variadicArgs = args[1].([]*client.ListOpts)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *RemoteProvider_GetAllS3_Call) Return(s3Remotes []client.S3Remote, err error) *RemoteProvider_GetAllS3_Call {
	_c.Call.Return(s3Remotes, err)
	return _c
}

func (_c *RemoteProvider_GetAllS3_Call) RunAndReturn(run func(ctx context.Context, opts ...*client.ListOpts) ([]client.S3Remote, error)) *RemoteProvider_GetAllS3_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyEbs provides a mock function for the type RemoteProvider
func (_mock *RemoteProvider) ModifyEbs(ctx context.Context, remoteName string, modify client.EbsRemote) error {
	ret := _mock.Called(ctx, remoteName, modify)

	if len(ret) == 0 {
		panic("no return value specified for ModifyEbs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.EbsRemote) error); ok {
		r0 = returnFunc(ctx, remoteName, modify)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RemoteProvider_ModifyEbs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyEbs'
type RemoteProvider_ModifyEbs_Call struct {
	*mock.Call
}

// ModifyEbs is a helper method to define mock.On call
//   - ctx context.Context
//   - remoteName string
//   - modify client.EbsRemote
func (_e *RemoteProvider_Expecter) ModifyEbs(ctx any, remoteName any, modify any) *RemoteProvider_ModifyEbs_Call {
	return &RemoteProvider_ModifyEbs_Call{Call: _e.mock.On("ModifyEbs", ctx, remoteName, modify)}
}

func (_c *RemoteProvider_ModifyEbs_Call) Run(run func(ctx context.Context, remoteName string, modify client.EbsRemote)) *RemoteProvider_ModifyEbs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.EbsRemote
		if args[2] != nil {
			arg2 = args[2].(client.EbsRemote)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RemoteProvider_ModifyEbs_Call) Return(err error) *RemoteProvider_ModifyEbs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RemoteProvider_ModifyEbs_Call) RunAndReturn(run func(ctx context.Context, remoteName string, modify client.EbsRemote) error) *RemoteProvider_ModifyEbs_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyLinstor provides a mock function for the type RemoteProvider
func (_mock *RemoteProvider) ModifyLinstor(ctx context.Context, remoteName string, modify client.LinstorRemote) error {
	ret := _mock.Called(ctx, remoteName, modify)

	if len(ret) == 0 {
		panic("no return value specified for ModifyLinstor")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.LinstorRemote) error); ok {
		r0 = returnFunc(ctx, remoteName, modify)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RemoteProvider_ModifyLinstor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyLinstor'
type RemoteProvider_ModifyLinstor_Call struct {
	*mock.Call
}

// ModifyLinstor is a helper method to define mock.On call
//   - ctx context.Context
//   - remoteName string
//   - modify client.LinstorRemote
func (_e *RemoteProvider_Expecter) ModifyLinstor(ctx any, remoteName any, modify any) *RemoteProvider_ModifyLinstor_Call {
	return &RemoteProvider_ModifyLinstor_Call{Call: _e.mock.On("ModifyLinstor", ctx, remoteName, modify)}
}

func (_c *RemoteProvider_ModifyLinstor_Call) Run(run func(ctx context.Context, remoteName string, modify client.LinstorRemote)) *RemoteProvider_ModifyLinstor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.LinstorRemote
		if args[2] != nil {
			arg2 = args[2].(client.LinstorRemote)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RemoteProvider_ModifyLinstor_Call) Return(err error) *RemoteProvider_ModifyLinstor_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RemoteProvider_ModifyLinstor_Call) RunAndReturn(run func(ctx context.Context, remoteName string, modify client.LinstorRemote) error) *RemoteProvider_ModifyLinstor_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyS3 provides a mock function for the type RemoteProvider
func (_mock *RemoteProvider) ModifyS3(ctx context.Context, remoteName string, modify client.S3Remote) error {
	ret := _mock.Called(ctx, remoteName, modify)

	if len(ret) == 0 {
		panic("no return value specified for ModifyS3")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.S3Remote) error); ok {
		r0 = returnFunc(ctx, remoteName, modify)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RemoteProvider_ModifyS3_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyS3'
type RemoteProvider_ModifyS3_Call struct {
	*mock.Call
}

// ModifyS3 is a helper method to define mock.On call
//   - ctx context.Context
//   - remoteName string
//   - modify client.S3Remote
func (_e *RemoteProvider_Expecter) ModifyS3(ctx any, remoteName any, modify any) *RemoteProvider_ModifyS3_Call {
	return &RemoteProvider_ModifyS3_Call{Call: _e.mock.On("ModifyS3", ctx, remoteName, modify)}
}

func (_c *RemoteProvider_ModifyS3_Call) Run(run func(ctx context.Context, remoteName string, modify client.S3Remote)) *RemoteProvider_ModifyS3_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.S3Remote
		if args[2] != nil {
			arg2 = args[2].(client.S3Remote)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RemoteProvider_ModifyS3_Call) Return(err error) *RemoteProvider_ModifyS3_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RemoteProvider_ModifyS3_Call) RunAndReturn(run func(ctx context.Context, remoteName string, modify client.S3Remote) error) *RemoteProvider_ModifyS3_Call {
	_c.Call.Return(run)
	return _c
}
