// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LINBIT/golinstor/client"
	mock "github.com/stretchr/testify/mock"
)

// NewResourceGroupProvider creates a new instance of ResourceGroupProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResourceGroupProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResourceGroupProvider {
	mock := &ResourceGroupProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ResourceGroupProvider is an autogenerated mock type for the ResourceGroupProvider type
type ResourceGroupProvider struct {
	mock.Mock
}

type ResourceGroupProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *ResourceGroupProvider) EXPECT() *ResourceGroupProvider_Expecter {
	return &ResourceGroupProvider_Expecter{mock: &_m.Mock}
}

// Adjust provides a mock function for the type ResourceGroupProvider
func (_mock *ResourceGroupProvider) Adjust(ctx context.Context, resGrpName string, adjust client.ResourceGroupAdjust) error {
	ret := _mock.Called(ctx, resGrpName, adjust)

	if len(ret) == 0 {
		panic("no return value specified for Adjust")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ResourceGroupAdjust) error); ok {
		r0 = returnFunc(ctx, resGrpName, adjust)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceGroupProvider_Adjust_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Adjust'
type ResourceGroupProvider_Adjust_Call struct {
	*mock.Call
}

// Adjust is a helper method to define mock.On call
//   - ctx context.Context
//   - resGrpName string
//   - adjust client.ResourceGroupAdjust
func (_e *ResourceGroupProvider_Expecter) Adjust(ctx any, resGrpName any, adjust any) *ResourceGroupProvider_Adjust_Call {
	return &ResourceGroupProvider_Adjust_Call{Call: _e.mock.On("Adjust", ctx, resGrpName, adjust)}
}

func (_c *ResourceGroupProvider_Adjust_Call) Run(run func(ctx context.Context, resGrpName string, adjust client.ResourceGroupAdjust)) *ResourceGroupProvider_Adjust_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ResourceGroupAdjust
		if args[2] != nil {
			arg2 = args[2].(client.ResourceGroupAdjust)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceGroupProvider_Adjust_Call) Return(err error) *ResourceGroupProvider_Adjust_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceGroupProvider_Adjust_Call) RunAndReturn(run func(ctx context.Context, resGrpName string, adjust client.ResourceGroupAdjust) error) *ResourceGroupProvider_Adjust_Call {
	_c.Call.Return(run)
	return _c
}

// AdjustAll provides a mock function for the type ResourceGroupProvider
func (_mock *ResourceGroupProvider) AdjustAll(ctx context.Context, adjust client.ResourceGroupAdjust) error {
	ret := _mock.Called(ctx, adjust)

	if len(ret) == 0 {
		panic("no return value specified for AdjustAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.ResourceGroupAdjust) error); ok {
		r0 = returnFunc(ctx, adjust)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceGroupProvider_AdjustAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdjustAll'
type ResourceGroupProvider_AdjustAll_Call struct {
	*mock.Call
}

// AdjustAll is a helper method to define mock.On call
//   - ctx context.Context
//   - adjust client.ResourceGroupAdjust
func (_e *ResourceGroupProvider_Expecter) AdjustAll(ctx any, adjust any) *ResourceGroupProvider_AdjustAll_Call {
	return &ResourceGroupProvider_AdjustAll_Call{Call: _e.mock.On("AdjustAll", ctx, adjust)}
}

func (_c *ResourceGroupProvider_AdjustAll_Call) Run(run func(ctx context.Context, adjust client.ResourceGroupAdjust)) *ResourceGroupProvider_AdjustAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.ResourceGroupAdjust
		if args[1] != nil {
			arg1 = args[1].(client.ResourceGroupAdjust)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResourceGroupProvider_AdjustAll_Call) Return(err error) *ResourceGroupProvider_AdjustAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceGroupProvider_AdjustAll_Call) RunAndReturn(run func(ctx context.Context, adjust client.ResourceGroupAdjust) error) *ResourceGroupProvider_AdjustAll_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type ResourceGroupProvider
func (_mock *ResourceGroupProvider) Create(ctx context.Context, resGrp client.ResourceGroup) error {
	ret := _mock.Called(ctx, resGrp)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.ResourceGroup) error); ok {
		r0 = returnFunc(ctx, resGrp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceGroupProvider_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ResourceGroupProvider_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - resGrp client.ResourceGroup
func (_e *ResourceGroupProvider_Expecter) Create(ctx any, resGrp any) *ResourceGroupProvider_Create_Call {
	return &ResourceGroupProvider_Create_Call{Call: _e.mock.On("Create", ctx, resGrp)}
}

func (_c *ResourceGroupProvider_Create_Call) Run(run func(ctx context.Context, resGrp client.ResourceGroup)) *ResourceGroupProvider_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.ResourceGroup
		if args[1] != nil {
			arg1 = args[1].(client.ResourceGroup)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResourceGroupProvider_Create_Call) Return(err error) *ResourceGroupProvider_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceGroupProvider_Create_Call) RunAndReturn(run func(ctx context.Context, resGrp client.ResourceGroup) error) *ResourceGroupProvider_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateVolumeGroup provides a mock function for the type ResourceGroupProvider
func (_mock *ResourceGroupProvider) CreateVolumeGroup(ctx context.Context, resGrpName string, volGrp client.VolumeGroup) error {
	ret := _mock.Called(ctx, resGrpName, volGrp)

	if len(ret) == 0 {
		panic("no return value specified for CreateVolumeGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.VolumeGroup) error); ok {
		r0 = returnFunc(ctx, resGrpName, volGrp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceGroupProvider_CreateVolumeGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVolumeGroup'
type ResourceGroupProvider_CreateVolumeGroup_Call struct {
	*mock.Call
}

// CreateVolumeGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - resGrpName string
//   - volGrp client.VolumeGroup
func (_e *ResourceGroupProvider_Expecter) CreateVolumeGroup(ctx any, resGrpName any, volGrp any) *ResourceGroupProvider_CreateVolumeGroup_Call {
	return &ResourceGroupProvider_CreateVolumeGroup_Call{Call: _e.mock.On("CreateVolumeGroup", ctx, resGrpName, volGrp)}
}

func (_c *ResourceGroupProvider_CreateVolumeGroup_Call) Run(run func(ctx context.Context, resGrpName string, volGrp client.VolumeGroup)) *ResourceGroupProvider_CreateVolumeGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.VolumeGroup
		if args[2] != nil {
			arg2 = args[2].(client.VolumeGroup)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceGroupProvider_CreateVolumeGroup_Call) Return(err error) *ResourceGroupProvider_CreateVolumeGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceGroupProvider_CreateVolumeGroup_Call) RunAndReturn(run func(ctx context.Context, resGrpName string, volGrp client.VolumeGroup) error) *ResourceGroupProvider_CreateVolumeGroup_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type ResourceGroupProvider
func (_mock *ResourceGroupProvider) Delete(ctx context.Context, resGrpName string) error {
	ret := _mock.Called(ctx, resGrpName)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, resGrpName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceGroupProvider_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ResourceGroupProvider_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - resGrpName string
func (_e *ResourceGroupProvider_Expecter) Delete(ctx any, resGrpName any) *ResourceGroupProvider_Delete_Call {
	return &ResourceGroupProvider_Delete_Call{Call: _e.mock.On("Delete", ctx, resGrpName)}
}

func (_c *ResourceGroupProvider_Delete_Call) Run(run func(ctx context.Context, resGrpName string)) *ResourceGroupProvider_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResourceGroupProvider_Delete_Call) Return(err error) *ResourceGroupProvider_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceGroupProvider_Delete_Call) RunAndReturn(run func(ctx context.Context, resGrpName string) error) *ResourceGroupProvider_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVolumeGroup provides a mock function for the type ResourceGroupProvider
func (_mock *ResourceGroupProvider) DeleteVolumeGroup(ctx context.Context, resGrpName string, volNr int) error {
	ret := _mock.Called(ctx, resGrpName, volNr)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVolumeGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = returnFunc(ctx, resGrpName, volNr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceGroupProvider_DeleteVolumeGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVolumeGroup'
type ResourceGroupProvider_DeleteVolumeGroup_Call struct {
	*mock.Call
}

// DeleteVolumeGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - resGrpName string
//   - volNr int
func (_e *ResourceGroupProvider_Expecter) DeleteVolumeGroup(ctx any, resGrpName any, volNr any) *ResourceGroupProvider_DeleteVolumeGroup_Call {
	return &ResourceGroupProvider_DeleteVolumeGroup_Call{Call: _e.mock.On("DeleteVolumeGroup", ctx, resGrpName, volNr)}
}

func (_c *ResourceGroupProvider_DeleteVolumeGroup_Call) Run(run func(ctx context.Context, resGrpName string, volNr int)) *ResourceGroupProvider_DeleteVolumeGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceGroupProvider_DeleteVolumeGroup_Call) Return(err error) *ResourceGroupProvider_DeleteVolumeGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceGroupProvider_DeleteVolumeGroup_Call) RunAndReturn(run func(ctx context.Context, resGrpName string, volNr int) error) *ResourceGroupProvider_DeleteVolumeGroup_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type ResourceGroupProvider
func (_mock *ResourceGroupProvider) Get(ctx context.Context, resGrpName string, opts ...*client.ListOpts) (client.ResourceGroup, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, resGrpName, opts)
	} else {
		tmpRet = _mock.Called(ctx, resGrpName)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 client.ResourceGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*client.ListOpts) (client.ResourceGroup, error)); ok {
		return returnFunc(ctx, resGrpName, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*client.ListOpts) client.ResourceGroup); ok {
		r0 = returnFunc(ctx, resGrpName, opts...)
	} else {
		r0 = ret.Get(0).(client.ResourceGroup)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...*client.ListOpts) error); ok {
		r1 = returnFunc(ctx, resGrpName, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceGroupProvider_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ResourceGroupProvider_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - resGrpName string
//   - opts ...*client.ListOpts
func (_e *ResourceGroupProvider_Expecter) Get(ctx any, resGrpName any, opts ...any) *ResourceGroupProvider_Get_Call {
	return &ResourceGroupProvider_Get_Call{Call: _e.mock.On("Get",
		append([]any{ctx, resGrpName}, opts...)...)}
}

func (_c *ResourceGroupProvider_Get_Call) Run(run func(ctx context.Context, resGrpName string, opts ...*client.ListOpts)) *ResourceGroupProvider_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*client.ListOpts
		var variadicArgs []*client.ListOpts
		if len(args) > 2 {
			variadicArgs = args[2].([]*client.ListOpts)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ResourceGroupProvider_Get_Call) Return(resourceGroup client.ResourceGroup, err error) *ResourceGroupProvider_Get_Call {
	_c.Call.Return(resourceGroup, err)
	return _c
}

func (_c *ResourceGroupProvider_Get_Call) RunAndReturn(run func(ctx context.Context, resGrpName string, opts ...*client.ListOpts) (client.ResourceGroup, error)) *ResourceGroupProvider_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type ResourceGroupProvider
func (_mock *ResourceGroupProvider) GetAll(ctx context.Context, opts ...*client.ListOpts) ([]client.ResourceGroup, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []client.ResourceGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*client.ListOpts) ([]client.ResourceGroup, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*client.ListOpts) []client.ResourceGroup); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.ResourceGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...*client.ListOpts) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceGroupProvider_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type ResourceGroupProvider_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...*client.ListOpts
func (_e *ResourceGroupProvider_Expecter) GetAll(ctx any, opts ...any) *ResourceGroupProvider_GetAll_Call {
	return &ResourceGroupProvider_GetAll_Call{Call: _e.mock.On("GetAll",
		append([]any{ctx}, opts...)...)}
}

func (_c *ResourceGroupProvider_GetAll_Call) Run(run func(ctx context.Context, opts ...*client.ListOpts)) *ResourceGroupProvider_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*client.ListOpts
		var variadicArgs []*client.ListOpts
		if len(args) > 1 {
			variadicArgs = args[1].([]*client.ListOpts)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *ResourceGroupProvider_GetAll_Call) Return(resourceGroups []client.ResourceGroup, err error) *ResourceGroupProvider_GetAll_Call {
	_c.Call.Return(resourceGroups, err)
	return _c
}

func (_c *ResourceGroupProvider_GetAll_Call) RunAndReturn(run func(ctx context.Context, opts ...*client.ListOpts) ([]client.ResourceGroup, error)) *ResourceGroupProvider_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropsInfos provides a mock function for the type ResourceGroupProvider
func (_mock *ResourceGroupProvider) GetPropsInfos(ctx context.Context, opts ...*client.ListOpts) ([]client.PropsInfo, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetPropsInfos")
	}

	var r0 []client.PropsInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*client.ListOpts) ([]client.PropsInfo, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*client.ListOpts) []client.PropsInfo); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.PropsInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...*client.ListOpts) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceGroupProvider_GetPropsInfos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropsInfos'
type ResourceGroupProvider_GetPropsInfos_Call struct {
	*mock.Call
}

// GetPropsInfos is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...*client.ListOpts
func (_e *ResourceGroupProvider_Expecter) GetPropsInfos(ctx any, opts ...any) *ResourceGroupProvider_GetPropsInfos_Call {
	return &ResourceGroupProvider_GetPropsInfos_Call{Call: _e.mock.On("GetPropsInfos",
		append([]any{ctx}, opts...)...)}
}

func (_c *ResourceGroupProvider_GetPropsInfos_Call) Run(run func(ctx context.Context, opts ...*client.ListOpts)) *ResourceGroupProvider_GetPropsInfos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*client.ListOpts
		var variadicArgs []*client.ListOpts
		if len(args) > 1 {
			variadicArgs = args[1].([]*client.ListOpts)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *ResourceGroupProvider_GetPropsInfos_Call) Return(propsInfos []client.PropsInfo, err error) *ResourceGroupProvider_GetPropsInfos_Call {
	_c.Call.Return(propsInfos, err)
	return _c
}

func (_c *ResourceGroupProvider_GetPropsInfos_Call) RunAndReturn(run func(ctx context.Context, opts ...*client.ListOpts) ([]client.PropsInfo, error)) *ResourceGroupProvider_GetPropsInfos_Call {
	_c.Call.Return(run)
	return _c
}

// GetVolumeGroup provides a mock function for the type ResourceGroupProvider
func (_mock *ResourceGroupProvider) GetVolumeGroup(ctx context.Context, resGrpName string, volNr int, opts ...*client.ListOpts) (client.VolumeGroup, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, resGrpName, volNr, opts)
	} else {
		tmpRet = _mock.Called(ctx, resGrpName, volNr)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetVolumeGroup")
	}

	var r0 client.VolumeGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, ...*client.ListOpts) (client.VolumeGroup, error)); ok {
		return returnFunc(ctx, resGrpName, volNr, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, ...*client.ListOpts) client.VolumeGroup); ok {
		r0 = returnFunc(ctx, resGrpName, volNr, opts...)
	} else {
		r0 = ret.Get(0).(client.VolumeGroup)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, ...*client.ListOpts) error); ok {
		r1 = returnFunc(ctx, resGrpName, volNr, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceGroupProvider_GetVolumeGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVolumeGroup'
type ResourceGroupProvider_GetVolumeGroup_Call struct {
	*mock.Call
}

// GetVolumeGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - resGrpName string
//   - volNr int
//   - opts ...*client.ListOpts
func (_e *ResourceGroupProvider_Expecter) GetVolumeGroup(ctx any, resGrpName any, volNr any, opts ...any) *ResourceGroupProvider_GetVolumeGroup_Call {
	return &ResourceGroupProvider_GetVolumeGroup_Call{Call: _e.mock.On("GetVolumeGroup",
		append([]any{ctx, resGrpName, volNr}, opts...)...)}
}

func (_c *ResourceGroupProvider_GetVolumeGroup_Call) Run(run func(ctx context.Context, resGrpName string, volNr int, opts ...*client.ListOpts)) *ResourceGroupProvider_GetVolumeGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 []*client.ListOpts
		var variadicArgs []*client.ListOpts
		if len(args) > 3 {
			variadicArgs = args[3].([]*client.ListOpts)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *ResourceGroupProvider_GetVolumeGroup_Call) Return(volumeGroup client.VolumeGroup, err error) *ResourceGroupProvider_GetVolumeGroup_Call {
	_c.Call.Return(volumeGroup, err)
	return _c
}

func (_c *ResourceGroupProvider_GetVolumeGroup_Call) RunAndReturn(run func(ctx context.Context, resGrpName string, volNr int, opts ...*client.ListOpts) (client.VolumeGroup, error)) *ResourceGroupProvider_GetVolumeGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetVolumeGroupPropsInfos provides a mock function for the type ResourceGroupProvider
func (_mock *ResourceGroupProvider) GetVolumeGroupPropsInfos(ctx context.Context, resGrpName string, opts ...*client.ListOpts) ([]client.PropsInfo, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, resGrpName, opts)
	} else {
		tmpRet = _mock.Called(ctx, resGrpName)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetVolumeGroupPropsInfos")
	}

	var r0 []client.PropsInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*client.ListOpts) ([]client.PropsInfo, error)); ok {
		return returnFunc(ctx, resGrpName, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*client.ListOpts) []client.PropsInfo); ok {
		r0 = returnFunc(ctx, resGrpName, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.PropsInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...*client.ListOpts) error); ok {
		r1 = returnFunc(ctx, resGrpName, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceGroupProvider_GetVolumeGroupPropsInfos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVolumeGroupPropsInfos'
type ResourceGroupProvider_GetVolumeGroupPropsInfos_Call struct {
	*mock.Call
}

// GetVolumeGroupPropsInfos is a helper method to define mock.On call
//   - ctx context.Context
//   - resGrpName string
//   - opts ...*client.ListOpts
func (_e *ResourceGroupProvider_Expecter) GetVolumeGroupPropsInfos(ctx any, resGrpName any, opts ...any) *ResourceGroupProvider_GetVolumeGroupPropsInfos_Call {
	return &ResourceGroupProvider_GetVolumeGroupPropsInfos_Call{Call: _e.mock.On("GetVolumeGroupPropsInfos",
		append([]any{ctx, resGrpName}, opts...)...)}
}

func (_c *ResourceGroupProvider_GetVolumeGroupPropsInfos_Call) Run(run func(ctx context.Context, resGrpName string, opts ...*client.ListOpts)) *ResourceGroupProvider_GetVolumeGroupPropsInfos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*client.ListOpts
		var variadicArgs []*client.ListOpts
		if len(args) > 2 {
			variadicArgs = args[2].([]*client.ListOpts)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ResourceGroupProvider_GetVolumeGroupPropsInfos_Call) Return(propsInfos []client.PropsInfo, err error) *ResourceGroupProvider_GetVolumeGroupPropsInfos_Call {
	_c.Call.Return(propsInfos, err)
	return _c
}

func (_c *ResourceGroupProvider_GetVolumeGroupPropsInfos_Call) RunAndReturn(run func(ctx context.Context, resGrpName string, opts ...*client.ListOpts) ([]client.PropsInfo, error)) *ResourceGroupProvider_GetVolumeGroupPropsInfos_Call {
	_c.Call.Return(run)
	return _c
}

// GetVolumeGroups provides a mock function for the type ResourceGroupProvider
func (_mock *ResourceGroupProvider) GetVolumeGroups(ctx context.Context, resGrpName string, opts ...*client.ListOpts) ([]client.VolumeGroup, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, resGrpName, opts)
	} else {
		tmpRet = _mock.Called(ctx, resGrpName)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetVolumeGroups")
	}

	var r0 []client.VolumeGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*client.ListOpts) ([]client.VolumeGroup, error)); ok {
		return returnFunc(ctx, resGrpName, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*client.ListOpts) []client.VolumeGroup); ok {
		r0 = returnFunc(ctx, resGrpName, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.VolumeGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...*client.ListOpts) error); ok {
		r1 = returnFunc(ctx, resGrpName, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceGroupProvider_GetVolumeGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVolumeGroups'
type ResourceGroupProvider_GetVolumeGroups_Call struct {
	*mock.Call
}

// GetVolumeGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - resGrpName string
//   - opts ...*client.ListOpts
func (_e *ResourceGroupProvider_Expecter) GetVolumeGroups(ctx any, resGrpName any, opts ...any) *ResourceGroupProvider_GetVolumeGroups_Call {
	return &ResourceGroupProvider_GetVolumeGroups_Call{Call: _e.mock.On("GetVolumeGroups",
		append([]any{ctx, resGrpName}, opts...)...)}
}

func (_c *ResourceGroupProvider_GetVolumeGroups_Call) Run(run func(ctx context.Context, resGrpName string, opts ...*client.ListOpts)) *ResourceGroupProvider_GetVolumeGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*client.ListOpts
		var variadicArgs []*client.ListOpts
		if len(args) > 2 {
			variadicArgs = args[2].([]*client.ListOpts)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ResourceGroupProvider_GetVolumeGroups_Call) Return(volumeGroups []client.VolumeGroup, err error) *ResourceGroupProvider_GetVolumeGroups_Call {
	_c.Call.Return(volumeGroups, err)
	return _c
}

func (_c *ResourceGroupProvider_GetVolumeGroups_Call) RunAndReturn(run func(ctx context.Context, resGrpName string, opts ...*client.ListOpts) ([]client.VolumeGroup, error)) *ResourceGroupProvider_GetVolumeGroups_Call {
	_c.Call.Return(run)
	return _c
}

// Modify provides a mock function for the type ResourceGroupProvider
func (_mock *ResourceGroupProvider) Modify(ctx context.Context, resGrpName string, props client.ResourceGroupModify) error {
	ret := _mock.Called(ctx, resGrpName, props)

	if len(ret) == 0 {
		panic("no return value specified for Modify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ResourceGroupModify) error); ok {
		r0 = returnFunc(ctx, resGrpName, props)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceGroupProvider_Modify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modify'
type ResourceGroupProvider_Modify_Call struct {
	*mock.Call
}

// Modify is a helper method to define mock.On call
//   - ctx context.Context
//   - resGrpName string
//   - props client.ResourceGroupModify
func (_e *ResourceGroupProvider_Expecter) Modify(ctx any, resGrpName any, props any) *ResourceGroupProvider_Modify_Call {
	return &ResourceGroupProvider_Modify_Call{Call: _e.mock.On("Modify", ctx, resGrpName, props)}
}

func (_c *ResourceGroupProvider_Modify_Call) Run(run func(ctx context.Context, resGrpName string, props client.ResourceGroupModify)) *ResourceGroupProvider_Modify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ResourceGroupModify
		if args[2] != nil {
			arg2 = args[2].(client.ResourceGroupModify)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceGroupProvider_Modify_Call) Return(err error) *ResourceGroupProvider_Modify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceGroupProvider_Modify_Call) RunAndReturn(run func(ctx context.Context, resGrpName string, props client.ResourceGroupModify) error) *ResourceGroupProvider_Modify_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyVolumeGroup provides a mock function for the type ResourceGroupProvider
func (_mock *ResourceGroupProvider) ModifyVolumeGroup(ctx context.Context, resGrpName string, volNr int, props client.VolumeGroupModify) error {
	ret := _mock.Called(ctx, resGrpName, volNr, props)

	if len(ret) == 0 {
		panic("no return value specified for ModifyVolumeGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, client.VolumeGroupModify) error); ok {
		r0 = returnFunc(ctx, resGrpName, volNr, props)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceGroupProvider_ModifyVolumeGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyVolumeGroup'
type ResourceGroupProvider_ModifyVolumeGroup_Call struct {
	*mock.Call
}

// ModifyVolumeGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - resGrpName string
//   - volNr int
//   - props client.VolumeGroupModify
func (_e *ResourceGroupProvider_Expecter) ModifyVolumeGroup(ctx any, resGrpName any, volNr any, props any) *ResourceGroupProvider_ModifyVolumeGroup_Call {
	return &ResourceGroupProvider_ModifyVolumeGroup_Call{Call: _e.mock.On("ModifyVolumeGroup", ctx, resGrpName, volNr, props)}
}

func (_c *ResourceGroupProvider_ModifyVolumeGroup_Call) Run(run func(ctx context.Context, resGrpName string, volNr int, props client.VolumeGroupModify)) *ResourceGroupProvider_ModifyVolumeGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 client.VolumeGroupModify
		if args[3] != nil {
			arg3 = args[3].(client.VolumeGroupModify)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceGroupProvider_ModifyVolumeGroup_Call) Return(err error) *ResourceGroupProvider_ModifyVolumeGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceGroupProvider_ModifyVolumeGroup_Call) RunAndReturn(run func(ctx context.Context, resGrpName string, volNr int, props client.VolumeGroupModify) error) *ResourceGroupProvider_ModifyVolumeGroup_Call {
	_c.Call.Return(run)
	return _c
}

// QuerySizeInfo provides a mock function for the type ResourceGroupProvider
func (_mock *ResourceGroupProvider) QuerySizeInfo(ctx context.Context, resGrpName string, req client.QuerySizeInfoRequest) (client.QuerySizeInfoResponse, error) {
	ret := _mock.Called(ctx, resGrpName, req)

	if len(ret) == 0 {
		panic("no return value specified for QuerySizeInfo")
	}

	var r0 client.QuerySizeInfoResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.QuerySizeInfoRequest) (client.QuerySizeInfoResponse, error)); ok {
		return returnFunc(ctx, resGrpName, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.QuerySizeInfoRequest) client.QuerySizeInfoResponse); ok {
		r0 = returnFunc(ctx, resGrpName, req)
	} else {
		r0 = ret.Get(0).(client.QuerySizeInfoResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.QuerySizeInfoRequest) error); ok {
		r1 = returnFunc(ctx, resGrpName, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceGroupProvider_QuerySizeInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QuerySizeInfo'
type ResourceGroupProvider_QuerySizeInfo_Call struct {
	*mock.Call
}

// QuerySizeInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - resGrpName string
//   - req client.QuerySizeInfoRequest
func (_e *ResourceGroupProvider_Expecter) QuerySizeInfo(ctx any, resGrpName any, req any) *ResourceGroupProvider_QuerySizeInfo_Call {
	return &ResourceGroupProvider_QuerySizeInfo_Call{Call: _e.mock.On("QuerySizeInfo", ctx, resGrpName, req)}
}

func (_c *ResourceGroupProvider_QuerySizeInfo_Call) Run(run func(ctx context.Context, resGrpName string, req client.QuerySizeInfoRequest)) *ResourceGroupProvider_QuerySizeInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.QuerySizeInfoRequest
		if args[2] != nil {
			arg2 = args[2].(client.QuerySizeInfoRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceGroupProvider_QuerySizeInfo_Call) Return(querySizeInfoResponse client.QuerySizeInfoResponse, err error) *ResourceGroupProvider_QuerySizeInfo_Call {
	_c.Call.Return(querySizeInfoResponse, err)
	return _c
}

func (_c *ResourceGroupProvider_QuerySizeInfo_Call) RunAndReturn(run func(ctx context.Context, resGrpName string, req client.QuerySizeInfoRequest) (client.QuerySizeInfoResponse, error)) *ResourceGroupProvider_QuerySizeInfo_Call {
	_c.Call.Return(run)
	return _c
}

// Spawn provides a mock function for the type ResourceGroupProvider
func (_mock *ResourceGroupProvider) Spawn(ctx context.Context, resGrpName string, resGrpSpwn client.ResourceGroupSpawn) error {
	ret := _mock.Called(ctx, resGrpName, resGrpSpwn)

	if len(ret) == 0 {
		panic("no return value specified for Spawn")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ResourceGroupSpawn) error); ok {
		r0 = returnFunc(ctx, resGrpName, resGrpSpwn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceGroupProvider_Spawn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Spawn'
type ResourceGroupProvider_Spawn_Call struct {
	*mock.Call
}

// Spawn is a helper method to define mock.On call
//   - ctx context.Context
//   - resGrpName string
//   - resGrpSpwn client.ResourceGroupSpawn
func (_e *ResourceGroupProvider_Expecter) Spawn(ctx any, resGrpName any, resGrpSpwn any) *ResourceGroupProvider_Spawn_Call {
	return &ResourceGroupProvider_Spawn_Call{Call: _e.mock.On("Spawn", ctx, resGrpName, resGrpSpwn)}
}

func (_c *ResourceGroupProvider_Spawn_Call) Run(run func(ctx context.Context, resGrpName string, resGrpSpwn client.ResourceGroupSpawn)) *ResourceGroupProvider_Spawn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ResourceGroupSpawn
		if args[2] != nil {
			arg2 = args[2].(client.ResourceGroupSpawn)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceGroupProvider_Spawn_Call) Return(err error) *ResourceGroupProvider_Spawn_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceGroupProvider_Spawn_Call) RunAndReturn(run func(ctx context.Context, resGrpName string, resGrpSpwn client.ResourceGroupSpawn) error) *ResourceGroupProvider_Spawn_Call {
	_c.Call.Return(run)
	return _c
}
