// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LINBIT/golinstor/client"
	mock "github.com/stretchr/testify/mock"
)

// NewResourceProvider creates a new instance of ResourceProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResourceProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResourceProvider {
	mock := &ResourceProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ResourceProvider is an autogenerated mock type for the ResourceProvider type
type ResourceProvider struct {
	mock.Mock
}

type ResourceProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *ResourceProvider) EXPECT() *ResourceProvider_Expecter {
	return &ResourceProvider_Expecter{mock: &_m.Mock}
}

// Activate provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) Activate(ctx context.Context, resName string, nodeName string) error {
	ret := _mock.Called(ctx, resName, nodeName)

	if len(ret) == 0 {
		panic("no return value specified for Activate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, resName, nodeName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceProvider_Activate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Activate'
type ResourceProvider_Activate_Call struct {
	*mock.Call
}

// Activate is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - nodeName string
func (_e *ResourceProvider_Expecter) Activate(ctx any, resName any, nodeName any) *ResourceProvider_Activate_Call {
	return &ResourceProvider_Activate_Call{Call: _e.mock.On("Activate", ctx, resName, nodeName)}
}

func (_c *ResourceProvider_Activate_Call) Run(run func(ctx context.Context, resName string, nodeName string)) *ResourceProvider_Activate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceProvider_Activate_Call) Return(err error) *ResourceProvider_Activate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceProvider_Activate_Call) RunAndReturn(run func(ctx context.Context, resName string, nodeName string) error) *ResourceProvider_Activate_Call {
	_c.Call.Return(run)
	return _c
}

// Autoplace provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) Autoplace(ctx context.Context, resName string, apr client.AutoPlaceRequest) error {
	ret := _mock.Called(ctx, resName, apr)

	if len(ret) == 0 {
		panic("no return value specified for Autoplace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.AutoPlaceRequest) error); ok {
		r0 = returnFunc(ctx, resName, apr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceProvider_Autoplace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Autoplace'
type ResourceProvider_Autoplace_Call struct {
	*mock.Call
}

// Autoplace is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - apr client.AutoPlaceRequest
func (_e *ResourceProvider_Expecter) Autoplace(ctx any, resName any, apr any) *ResourceProvider_Autoplace_Call {
	return &ResourceProvider_Autoplace_Call{Call: _e.mock.On("Autoplace", ctx, resName, apr)}
}

func (_c *ResourceProvider_Autoplace_Call) Run(run func(ctx context.Context, resName string, apr client.AutoPlaceRequest)) *ResourceProvider_Autoplace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.AutoPlaceRequest
		if args[2] != nil {
			arg2 = args[2].(client.AutoPlaceRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceProvider_Autoplace_Call) Return(err error) *ResourceProvider_Autoplace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceProvider_Autoplace_Call) RunAndReturn(run func(ctx context.Context, resName string, apr client.AutoPlaceRequest) error) *ResourceProvider_Autoplace_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) Create(ctx context.Context, res client.ResourceCreate) error {
	ret := _mock.Called(ctx, res)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.ResourceCreate) error); ok {
		r0 = returnFunc(ctx, res)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceProvider_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ResourceProvider_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - res client.ResourceCreate
func (_e *ResourceProvider_Expecter) Create(ctx any, res any) *ResourceProvider_Create_Call {
	return &ResourceProvider_Create_Call{Call: _e.mock.On("Create", ctx, res)}
}

func (_c *ResourceProvider_Create_Call) Run(run func(ctx context.Context, res client.ResourceCreate)) *ResourceProvider_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.ResourceCreate
		if args[1] != nil {
			arg1 = args[1].(client.ResourceCreate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResourceProvider_Create_Call) Return(err error) *ResourceProvider_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceProvider_Create_Call) RunAndReturn(run func(ctx context.Context, res client.ResourceCreate) error) *ResourceProvider_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSnapshot provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) CreateSnapshot(ctx context.Context, snapshot client.Snapshot) error {
	ret := _mock.Called(ctx, snapshot)

	if len(ret) == 0 {
		panic("no return value specified for CreateSnapshot")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.Snapshot) error); ok {
		r0 = returnFunc(ctx, snapshot)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceProvider_CreateSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSnapshot'
type ResourceProvider_CreateSnapshot_Call struct {
	*mock.Call
}

// CreateSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - snapshot client.Snapshot
func (_e *ResourceProvider_Expecter) CreateSnapshot(ctx any, snapshot any) *ResourceProvider_CreateSnapshot_Call {
	return &ResourceProvider_CreateSnapshot_Call{Call: _e.mock.On("CreateSnapshot", ctx, snapshot)}
}

func (_c *ResourceProvider_CreateSnapshot_Call) Run(run func(ctx context.Context, snapshot client.Snapshot)) *ResourceProvider_CreateSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.Snapshot
		if args[1] != nil {
			arg1 = args[1].(client.Snapshot)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResourceProvider_CreateSnapshot_Call) Return(err error) *ResourceProvider_CreateSnapshot_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceProvider_CreateSnapshot_Call) RunAndReturn(run func(ctx context.Context, snapshot client.Snapshot) error) *ResourceProvider_CreateSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSnapshots provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) CreateSnapshots(ctx context.Context, snapshot ...client.Snapshot) error {
	var tmpRet mock.Arguments
	if len(snapshot) > 0 {
		tmpRet = _mock.Called(ctx, snapshot)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateSnapshots")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...client.Snapshot) error); ok {
		r0 = returnFunc(ctx, snapshot...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceProvider_CreateSnapshots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSnapshots'
type ResourceProvider_CreateSnapshots_Call struct {
	*mock.Call
}

// CreateSnapshots is a helper method to define mock.On call
//   - ctx context.Context
//   - snapshot ...client.Snapshot
func (_e *ResourceProvider_Expecter) CreateSnapshots(ctx any, snapshot ...any) *ResourceProvider_CreateSnapshots_Call {
	return &ResourceProvider_CreateSnapshots_Call{Call: _e.mock.On("CreateSnapshots",
		append([]any{ctx}, snapshot...)...)}
}

func (_c *ResourceProvider_CreateSnapshots_Call) Run(run func(ctx context.Context, snapshot ...client.Snapshot)) *ResourceProvider_CreateSnapshots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []client.Snapshot
		var variadicArgs []client.Snapshot
		if len(args) > 1 {
			variadicArgs = args[1].([]client.Snapshot)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *ResourceProvider_CreateSnapshots_Call) Return(err error) *ResourceProvider_CreateSnapshots_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceProvider_CreateSnapshots_Call) RunAndReturn(run func(ctx context.Context, snapshot ...client.Snapshot) error) *ResourceProvider_CreateSnapshots_Call {
	_c.Call.Return(run)
	return _c
}

// Deactivate provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) Deactivate(ctx context.Context, resName string, nodeName string) error {
	ret := _mock.Called(ctx, resName, nodeName)

	if len(ret) == 0 {
		panic("no return value specified for Deactivate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, resName, nodeName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceProvider_Deactivate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deactivate'
type ResourceProvider_Deactivate_Call struct {
	*mock.Call
}

// Deactivate is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - nodeName string
func (_e *ResourceProvider_Expecter) Deactivate(ctx any, resName any, nodeName any) *ResourceProvider_Deactivate_Call {
	return &ResourceProvider_Deactivate_Call{Call: _e.mock.On("Deactivate", ctx, resName, nodeName)}
}

func (_c *ResourceProvider_Deactivate_Call) Run(run func(ctx context.Context, resName string, nodeName string)) *ResourceProvider_Deactivate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceProvider_Deactivate_Call) Return(err error) *ResourceProvider_Deactivate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceProvider_Deactivate_Call) RunAndReturn(run func(ctx context.Context, resName string, nodeName string) error) *ResourceProvider_Deactivate_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) Delete(ctx context.Context, resName string, nodeName string, opts ...*client.ResourceDeleteOpts) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, resName, nodeName, opts)
	} else {
		tmpRet = _mock.Called(ctx, resName, nodeName)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...*client.ResourceDeleteOpts) error); ok {
		r0 = returnFunc(ctx, resName, nodeName, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceProvider_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ResourceProvider_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - nodeName string
//   - opts ...*client.ResourceDeleteOpts
func (_e *ResourceProvider_Expecter) Delete(ctx any, resName any, nodeName any, opts ...any) *ResourceProvider_Delete_Call {
	return &ResourceProvider_Delete_Call{Call: _e.mock.On("Delete",
		append([]any{ctx, resName, nodeName}, opts...)...)}
}

func (_c *ResourceProvider_Delete_Call) Run(run func(ctx context.Context, resName string, nodeName string, opts ...*client.ResourceDeleteOpts)) *ResourceProvider_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []*client.ResourceDeleteOpts
		var variadicArgs []*client.ResourceDeleteOpts
		if len(args) > 3 {
			variadicArgs = args[3].([]*client.ResourceDeleteOpts)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *ResourceProvider_Delete_Call) Return(err error) *ResourceProvider_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceProvider_Delete_Call) RunAndReturn(run func(ctx context.Context, resName string, nodeName string, opts ...*client.ResourceDeleteOpts) error) *ResourceProvider_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSnapshot provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) DeleteSnapshot(ctx context.Context, resName string, snapName string, opts ...*client.SnapshotDeleteOpts) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, resName, snapName, opts)
	} else {
		tmpRet = _mock.Called(ctx, resName, snapName)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteSnapshot")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...*client.SnapshotDeleteOpts) error); ok {
		r0 = returnFunc(ctx, resName, snapName, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceProvider_DeleteSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSnapshot'
type ResourceProvider_DeleteSnapshot_Call struct {
	*mock.Call
}

// DeleteSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - snapName string
//   - opts ...*client.SnapshotDeleteOpts
func (_e *ResourceProvider_Expecter) DeleteSnapshot(ctx any, resName any, snapName any, opts ...any) *ResourceProvider_DeleteSnapshot_Call {
	return &ResourceProvider_DeleteSnapshot_Call{Call: _e.mock.On("DeleteSnapshot",
		append([]any{ctx, resName, snapName}, opts...)...)}
}

func (_c *ResourceProvider_DeleteSnapshot_Call) Run(run func(ctx context.Context, resName string, snapName string, opts ...*client.SnapshotDeleteOpts)) *ResourceProvider_DeleteSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []*client.SnapshotDeleteOpts
		var variadicArgs []*client.SnapshotDeleteOpts
		if len(args) > 3 {
			variadicArgs = args[3].([]*client.SnapshotDeleteOpts)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *ResourceProvider_DeleteSnapshot_Call) Return(err error) *ResourceProvider_DeleteSnapshot_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceProvider_DeleteSnapshot_Call) RunAndReturn(run func(ctx context.Context, resName string, snapName string, opts ...*client.SnapshotDeleteOpts) error) *ResourceProvider_DeleteSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// DisableDRBDProxy provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) DisableDRBDProxy(ctx context.Context, resName string, nodeAName string, nodeBName string) error {
	ret := _mock.Called(ctx, resName, nodeAName, nodeBName)

	if len(ret) == 0 {
		panic("no return value specified for DisableDRBDProxy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, resName, nodeAName, nodeBName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceProvider_DisableDRBDProxy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableDRBDProxy'
type ResourceProvider_DisableDRBDProxy_Call struct {
	*mock.Call
}

// DisableDRBDProxy is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - nodeAName string
//   - nodeBName string
func (_e *ResourceProvider_Expecter) DisableDRBDProxy(ctx any, resName any, nodeAName any, nodeBName any) *ResourceProvider_DisableDRBDProxy_Call {
	return &ResourceProvider_DisableDRBDProxy_Call{Call: _e.mock.On("DisableDRBDProxy", ctx, resName, nodeAName, nodeBName)}
}

func (_c *ResourceProvider_DisableDRBDProxy_Call) Run(run func(ctx context.Context, resName string, nodeAName string, nodeBName string)) *ResourceProvider_DisableDRBDProxy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceProvider_DisableDRBDProxy_Call) Return(err error) *ResourceProvider_DisableDRBDProxy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceProvider_DisableDRBDProxy_Call) RunAndReturn(run func(ctx context.Context, resName string, nodeAName string, nodeBName string) error) *ResourceProvider_DisableDRBDProxy_Call {
	_c.Call.Return(run)
	return _c
}

// Diskful provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) Diskful(ctx context.Context, resName string, nodeName string, storagePoolName string, props *client.ToggleDiskDiskfulProps) error {
	ret := _mock.Called(ctx, resName, nodeName, storagePoolName, props)

	if len(ret) == 0 {
		panic("no return value specified for Diskful")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *client.ToggleDiskDiskfulProps) error); ok {
		r0 = returnFunc(ctx, resName, nodeName, storagePoolName, props)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceProvider_Diskful_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Diskful'
type ResourceProvider_Diskful_Call struct {
	*mock.Call
}

// Diskful is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - nodeName string
//   - storagePoolName string
//   - props *client.ToggleDiskDiskfulProps
func (_e *ResourceProvider_Expecter) Diskful(ctx any, resName any, nodeName any, storagePoolName any, props any) *ResourceProvider_Diskful_Call {
	return &ResourceProvider_Diskful_Call{Call: _e.mock.On("Diskful", ctx, resName, nodeName, storagePoolName, props)}
}

func (_c *ResourceProvider_Diskful_Call) Run(run func(ctx context.Context, resName string, nodeName string, storagePoolName string, props *client.ToggleDiskDiskfulProps)) *ResourceProvider_Diskful_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *client.ToggleDiskDiskfulProps
		if args[4] != nil {
			arg4 = args[4].(*client.ToggleDiskDiskfulProps)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ResourceProvider_Diskful_Call) Return(err error) *ResourceProvider_Diskful_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceProvider_Diskful_Call) RunAndReturn(run func(ctx context.Context, resName string, nodeName string, storagePoolName string, props *client.ToggleDiskDiskfulProps) error) *ResourceProvider_Diskful_Call {
	_c.Call.Return(run)
	return _c
}

// Diskless provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) Diskless(ctx context.Context, resName string, nodeName string, disklessPoolName string) error {
	ret := _mock.Called(ctx, resName, nodeName, disklessPoolName)

	if len(ret) == 0 {
		panic("no return value specified for Diskless")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, resName, nodeName, disklessPoolName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceProvider_Diskless_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Diskless'
type ResourceProvider_Diskless_Call struct {
	*mock.Call
}

// Diskless is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - nodeName string
//   - disklessPoolName string
func (_e *ResourceProvider_Expecter) Diskless(ctx any, resName any, nodeName any, disklessPoolName any) *ResourceProvider_Diskless_Call {
	return &ResourceProvider_Diskless_Call{Call: _e.mock.On("Diskless", ctx, resName, nodeName, disklessPoolName)}
}

func (_c *ResourceProvider_Diskless_Call) Run(run func(ctx context.Context, resName string, nodeName string, disklessPoolName string)) *ResourceProvider_Diskless_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceProvider_Diskless_Call) Return(err error) *ResourceProvider_Diskless_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceProvider_Diskless_Call) RunAndReturn(run func(ctx context.Context, resName string, nodeName string, disklessPoolName string) error) *ResourceProvider_Diskless_Call {
	_c.Call.Return(run)
	return _c
}

// EnableDRBDProxy provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) EnableDRBDProxy(ctx context.Context, resName string, nodeAName string, nodeBName string) error {
	ret := _mock.Called(ctx, resName, nodeAName, nodeBName)

	if len(ret) == 0 {
		panic("no return value specified for EnableDRBDProxy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, resName, nodeAName, nodeBName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceProvider_EnableDRBDProxy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableDRBDProxy'
type ResourceProvider_EnableDRBDProxy_Call struct {
	*mock.Call
}

// EnableDRBDProxy is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - nodeAName string
//   - nodeBName string
func (_e *ResourceProvider_Expecter) EnableDRBDProxy(ctx any, resName any, nodeAName any, nodeBName any) *ResourceProvider_EnableDRBDProxy_Call {
	return &ResourceProvider_EnableDRBDProxy_Call{Call: _e.mock.On("EnableDRBDProxy", ctx, resName, nodeAName, nodeBName)}
}

func (_c *ResourceProvider_EnableDRBDProxy_Call) Run(run func(ctx context.Context, resName string, nodeAName string, nodeBName string)) *ResourceProvider_EnableDRBDProxy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceProvider_EnableDRBDProxy_Call) Return(err error) *ResourceProvider_EnableDRBDProxy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceProvider_EnableDRBDProxy_Call) RunAndReturn(run func(ctx context.Context, resName string, nodeAName string, nodeBName string) error) *ResourceProvider_EnableDRBDProxy_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) Get(ctx context.Context, resName string, nodeName string, opts ...*client.ListOpts) (client.Resource, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, resName, nodeName, opts)
	} else {
		tmpRet = _mock.Called(ctx, resName, nodeName)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 client.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...*client.ListOpts) (client.Resource, error)); ok {
		return returnFunc(ctx, resName, nodeName, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...*client.ListOpts) client.Resource); ok {
		r0 = returnFunc(ctx, resName, nodeName, opts...)
	} else {
		r0 = ret.Get(0).(client.Resource)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, ...*client.ListOpts) error); ok {
		r1 = returnFunc(ctx, resName, nodeName, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceProvider_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ResourceProvider_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - nodeName string
//   - opts ...*client.ListOpts
func (_e *ResourceProvider_Expecter) Get(ctx any, resName any, nodeName any, opts ...any) *ResourceProvider_Get_Call {
	return &ResourceProvider_Get_Call{Call: _e.mock.On("Get",
		append([]any{ctx, resName, nodeName}, opts...)...)}
}

func (_c *ResourceProvider_Get_Call) Run(run func(ctx context.Context, resName string, nodeName string, opts ...*client.ListOpts)) *ResourceProvider_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []*client.ListOpts
		var variadicArgs []*client.ListOpts
		if len(args) > 3 {
			variadicArgs = args[3].([]*client.ListOpts)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *ResourceProvider_Get_Call) Return(resource client.Resource, err error) *ResourceProvider_Get_Call {
	_c.Call.Return(resource, err)
	return _c
}

func (_c *ResourceProvider_Get_Call) RunAndReturn(run func(ctx context.Context, resName string, nodeName string, opts ...*client.ListOpts) (client.Resource, error)) *ResourceProvider_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) GetAll(ctx context.Context, resName string, opts ...*client.ListOpts) ([]client.Resource, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, resName, opts)
	} else {
		tmpRet = _mock.Called(ctx, resName)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []client.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*client.ListOpts) ([]client.Resource, error)); ok {
		return returnFunc(ctx, resName, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*client.ListOpts) []client.Resource); ok {
		r0 = returnFunc(ctx, resName, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...*client.ListOpts) error); ok {
		r1 = returnFunc(ctx, resName, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceProvider_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type ResourceProvider_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - opts ...*client.ListOpts
func (_e *ResourceProvider_Expecter) GetAll(ctx any, resName any, opts ...any) *ResourceProvider_GetAll_Call {
	return &ResourceProvider_GetAll_Call{Call: _e.mock.On("GetAll",
		append([]any{ctx, resName}, opts...)...)}
}

func (_c *ResourceProvider_GetAll_Call) Run(run func(ctx context.Context, resName string, opts ...*client.ListOpts)) *ResourceProvider_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*client.ListOpts
		var variadicArgs []*client.ListOpts
		if len(args) > 2 {
			variadicArgs = args[2].([]*client.ListOpts)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ResourceProvider_GetAll_Call) Return(resources []client.Resource, err error) *ResourceProvider_GetAll_Call {
	_c.Call.Return(resources, err)
	return _c
}

func (_c *ResourceProvider_GetAll_Call) RunAndReturn(run func(ctx context.Context, resName string, opts ...*client.ListOpts) ([]client.Resource, error)) *ResourceProvider_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectionPropsInfos provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) GetConnectionPropsInfos(ctx context.Context, resName string, opts ...*client.ListOpts) ([]client.PropsInfo, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, resName, opts)
	} else {
		tmpRet = _mock.Called(ctx, resName)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionPropsInfos")
	}

	var r0 []client.PropsInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*client.ListOpts) ([]client.PropsInfo, error)); ok {
		return returnFunc(ctx, resName, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*client.ListOpts) []client.PropsInfo); ok {
		r0 = returnFunc(ctx, resName, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.PropsInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...*client.ListOpts) error); ok {
		r1 = returnFunc(ctx, resName, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceProvider_GetConnectionPropsInfos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectionPropsInfos'
type ResourceProvider_GetConnectionPropsInfos_Call struct {
	*mock.Call
}

// GetConnectionPropsInfos is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - opts ...*client.ListOpts
func (_e *ResourceProvider_Expecter) GetConnectionPropsInfos(ctx any, resName any, opts ...any) *ResourceProvider_GetConnectionPropsInfos_Call {
	return &ResourceProvider_GetConnectionPropsInfos_Call{Call: _e.mock.On("GetConnectionPropsInfos",
		append([]any{ctx, resName}, opts...)...)}
}

func (_c *ResourceProvider_GetConnectionPropsInfos_Call) Run(run func(ctx context.Context, resName string, opts ...*client.ListOpts)) *ResourceProvider_GetConnectionPropsInfos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*client.ListOpts
		var variadicArgs []*client.ListOpts
		if len(args) > 2 {
			variadicArgs = args[2].([]*client.ListOpts)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ResourceProvider_GetConnectionPropsInfos_Call) Return(propsInfos []client.PropsInfo, err error) *ResourceProvider_GetConnectionPropsInfos_Call {
	_c.Call.Return(propsInfos, err)
	return _c
}

func (_c *ResourceProvider_GetConnectionPropsInfos_Call) RunAndReturn(run func(ctx context.Context, resName string, opts ...*client.ListOpts) ([]client.PropsInfo, error)) *ResourceProvider_GetConnectionPropsInfos_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnections provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) GetConnections(ctx context.Context, resName string, nodeAName string, nodeBName string, opts ...*client.ListOpts) ([]client.ResourceConnection, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, resName, nodeAName, nodeBName, opts)
	} else {
		tmpRet = _mock.Called(ctx, resName, nodeAName, nodeBName)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetConnections")
	}

	var r0 []client.ResourceConnection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, ...*client.ListOpts) ([]client.ResourceConnection, error)); ok {
		return returnFunc(ctx, resName, nodeAName, nodeBName, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, ...*client.ListOpts) []client.ResourceConnection); ok {
		r0 = returnFunc(ctx, resName, nodeAName, nodeBName, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.ResourceConnection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, ...*client.ListOpts) error); ok {
		r1 = returnFunc(ctx, resName, nodeAName, nodeBName, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceProvider_GetConnections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnections'
type ResourceProvider_GetConnections_Call struct {
	*mock.Call
}

// GetConnections is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - nodeAName string
//   - nodeBName string
//   - opts ...*client.ListOpts
func (_e *ResourceProvider_Expecter) GetConnections(ctx any, resName any, nodeAName any, nodeBName any, opts ...any) *ResourceProvider_GetConnections_Call {
	return &ResourceProvider_GetConnections_Call{Call: _e.mock.On("GetConnections",
		append([]any{ctx, resName, nodeAName, nodeBName}, opts...)...)}
}

func (_c *ResourceProvider_GetConnections_Call) Run(run func(ctx context.Context, resName string, nodeAName string, nodeBName string, opts ...*client.ListOpts)) *ResourceProvider_GetConnections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []*client.ListOpts
		var variadicArgs []*client.ListOpts
		if len(args) > 4 {
			variadicArgs = args[4].([]*client.ListOpts)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *ResourceProvider_GetConnections_Call) Return(resourceConnections []client.ResourceConnection, err error) *ResourceProvider_GetConnections_Call {
	_c.Call.Return(resourceConnections, err)
	return _c
}

func (_c *ResourceProvider_GetConnections_Call) RunAndReturn(run func(ctx context.Context, resName string, nodeAName string, nodeBName string, opts ...*client.ListOpts) ([]client.ResourceConnection, error)) *ResourceProvider_GetConnections_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropsInfos provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) GetPropsInfos(ctx context.Context, resName string, opts ...*client.ListOpts) ([]client.PropsInfo, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, resName, opts)
	} else {
		tmpRet = _mock.Called(ctx, resName)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetPropsInfos")
	}

	var r0 []client.PropsInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*client.ListOpts) ([]client.PropsInfo, error)); ok {
		return returnFunc(ctx, resName, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*client.ListOpts) []client.PropsInfo); ok {
		r0 = returnFunc(ctx, resName, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.PropsInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...*client.ListOpts) error); ok {
		r1 = returnFunc(ctx, resName, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceProvider_GetPropsInfos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropsInfos'
type ResourceProvider_GetPropsInfos_Call struct {
	*mock.Call
}

// GetPropsInfos is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - opts ...*client.ListOpts
func (_e *ResourceProvider_Expecter) GetPropsInfos(ctx any, resName any, opts ...any) *ResourceProvider_GetPropsInfos_Call {
	return &ResourceProvider_GetPropsInfos_Call{Call: _e.mock.On("GetPropsInfos",
		append([]any{ctx, resName}, opts...)...)}
}

func (_c *ResourceProvider_GetPropsInfos_Call) Run(run func(ctx context.Context, resName string, opts ...*client.ListOpts)) *ResourceProvider_GetPropsInfos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*client.ListOpts
		var variadicArgs []*client.ListOpts
		if len(args) > 2 {
			variadicArgs = args[2].([]*client.ListOpts)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ResourceProvider_GetPropsInfos_Call) Return(propsInfos []client.PropsInfo, err error) *ResourceProvider_GetPropsInfos_Call {
	_c.Call.Return(propsInfos, err)
	return _c
}

func (_c *ResourceProvider_GetPropsInfos_Call) RunAndReturn(run func(ctx context.Context, resName string, opts ...*client.ListOpts) ([]client.PropsInfo, error)) *ResourceProvider_GetPropsInfos_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceView provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) GetResourceView(ctx context.Context, opts ...*client.ListOpts) ([]client.ResourceWithVolumes, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetResourceView")
	}

	var r0 []client.ResourceWithVolumes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*client.ListOpts) ([]client.ResourceWithVolumes, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*client.ListOpts) []client.ResourceWithVolumes); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.ResourceWithVolumes)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...*client.ListOpts) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceProvider_GetResourceView_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceView'
type ResourceProvider_GetResourceView_Call struct {
	*mock.Call
}

// GetResourceView is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...*client.ListOpts
func (_e *ResourceProvider_Expecter) GetResourceView(ctx any, opts ...any) *ResourceProvider_GetResourceView_Call {
	return &ResourceProvider_GetResourceView_Call{Call: _e.mock.On("GetResourceView",
		append([]any{ctx}, opts...)...)}
}

func (_c *ResourceProvider_GetResourceView_Call) Run(run func(ctx context.Context, opts ...*client.ListOpts)) *ResourceProvider_GetResourceView_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*client.ListOpts
		var variadicArgs []*client.ListOpts
		if len(args) > 1 {
			variadicArgs = args[1].([]*client.ListOpts)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *ResourceProvider_GetResourceView_Call) Return(resourceWithVolumess []client.ResourceWithVolumes, err error) *ResourceProvider_GetResourceView_Call {
	_c.Call.Return(resourceWithVolumess, err)
	return _c
}

func (_c *ResourceProvider_GetResourceView_Call) RunAndReturn(run func(ctx context.Context, opts ...*client.ListOpts) ([]client.ResourceWithVolumes, error)) *ResourceProvider_GetResourceView_Call {
	_c.Call.Return(run)
	return _c
}

// GetSnapshot provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) GetSnapshot(ctx context.Context, resName string, snapName string, opts ...*client.ListOpts) (client.Snapshot, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, resName, snapName, opts)
	} else {
		tmpRet = _mock.Called(ctx, resName, snapName)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetSnapshot")
	}

	var r0 client.Snapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...*client.ListOpts) (client.Snapshot, error)); ok {
		return returnFunc(ctx, resName, snapName, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...*client.ListOpts) client.Snapshot); ok {
		r0 = returnFunc(ctx, resName, snapName, opts...)
	} else {
		r0 = ret.Get(0).(client.Snapshot)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, ...*client.ListOpts) error); ok {
		r1 = returnFunc(ctx, resName, snapName, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceProvider_GetSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSnapshot'
type ResourceProvider_GetSnapshot_Call struct {
	*mock.Call
}

// GetSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - snapName string
//   - opts ...*client.ListOpts
func (_e *ResourceProvider_Expecter) GetSnapshot(ctx any, resName any, snapName any, opts ...any) *ResourceProvider_GetSnapshot_Call {
	return &ResourceProvider_GetSnapshot_Call{Call: _e.mock.On("GetSnapshot",
		append([]any{ctx, resName, snapName}, opts...)...)}
}

func (_c *ResourceProvider_GetSnapshot_Call) Run(run func(ctx context.Context, resName string, snapName string, opts ...*client.ListOpts)) *ResourceProvider_GetSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []*client.ListOpts
		var variadicArgs []*client.ListOpts
		if len(args) > 3 {
			variadicArgs = args[3].([]*client.ListOpts)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *ResourceProvider_GetSnapshot_Call) Return(snapshot client.Snapshot, err error) *ResourceProvider_GetSnapshot_Call {
	_c.Call.Return(snapshot, err)
	return _c
}

func (_c *ResourceProvider_GetSnapshot_Call) RunAndReturn(run func(ctx context.Context, resName string, snapName string, opts ...*client.ListOpts) (client.Snapshot, error)) *ResourceProvider_GetSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// GetSnapshotView provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) GetSnapshotView(ctx context.Context, opts ...*client.ListOpts) ([]client.Snapshot, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetSnapshotView")
	}

	var r0 []client.Snapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*client.ListOpts) ([]client.Snapshot, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*client.ListOpts) []client.Snapshot); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.Snapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...*client.ListOpts) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceProvider_GetSnapshotView_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSnapshotView'
type ResourceProvider_GetSnapshotView_Call struct {
	*mock.Call
}

// GetSnapshotView is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...*client.ListOpts
func (_e *ResourceProvider_Expecter) GetSnapshotView(ctx any, opts ...any) *ResourceProvider_GetSnapshotView_Call {
	return &ResourceProvider_GetSnapshotView_Call{Call: _e.mock.On("GetSnapshotView",
		append([]any{ctx}, opts...)...)}
}

func (_c *ResourceProvider_GetSnapshotView_Call) Run(run func(ctx context.Context, opts ...*client.ListOpts)) *ResourceProvider_GetSnapshotView_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*client.ListOpts
		var variadicArgs []*client.ListOpts
		if len(args) > 1 {
			variadicArgs = args[1].([]*client.ListOpts)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *ResourceProvider_GetSnapshotView_Call) Return(snapshots []client.Snapshot, err error) *ResourceProvider_GetSnapshotView_Call {
	_c.Call.Return(snapshots, err)
	return _c
}

func (_c *ResourceProvider_GetSnapshotView_Call) RunAndReturn(run func(ctx context.Context, opts ...*client.ListOpts) ([]client.Snapshot, error)) *ResourceProvider_GetSnapshotView_Call {
	_c.Call.Return(run)
	return _c
}

// GetSnapshots provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) GetSnapshots(ctx context.Context, resName string, opts ...*client.ListOpts) ([]client.Snapshot, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, resName, opts)
	} else {
		tmpRet = _mock.Called(ctx, resName)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetSnapshots")
	}

	var r0 []client.Snapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*client.ListOpts) ([]client.Snapshot, error)); ok {
		return returnFunc(ctx, resName, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*client.ListOpts) []client.Snapshot); ok {
		r0 = returnFunc(ctx, resName, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.Snapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...*client.ListOpts) error); ok {
		r1 = returnFunc(ctx, resName, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceProvider_GetSnapshots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSnapshots'
type ResourceProvider_GetSnapshots_Call struct {
	*mock.Call
}

// GetSnapshots is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - opts ...*client.ListOpts
func (_e *ResourceProvider_Expecter) GetSnapshots(ctx any, resName any, opts ...any) *ResourceProvider_GetSnapshots_Call {
	return &ResourceProvider_GetSnapshots_Call{Call: _e.mock.On("GetSnapshots",
		append([]any{ctx, resName}, opts...)...)}
}

func (_c *ResourceProvider_GetSnapshots_Call) Run(run func(ctx context.Context, resName string, opts ...*client.ListOpts)) *ResourceProvider_GetSnapshots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*client.ListOpts
		var variadicArgs []*client.ListOpts
		if len(args) > 2 {
			variadicArgs = args[2].([]*client.ListOpts)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ResourceProvider_GetSnapshots_Call) Return(snapshots []client.Snapshot, err error) *ResourceProvider_GetSnapshots_Call {
	_c.Call.Return(snapshots, err)
	return _c
}

func (_c *ResourceProvider_GetSnapshots_Call) RunAndReturn(run func(ctx context.Context, resName string, opts ...*client.ListOpts) ([]client.Snapshot, error)) *ResourceProvider_GetSnapshots_Call {
	_c.Call.Return(run)
	return _c
}

// GetVolume provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) GetVolume(ctx context.Context, resName string, nodeName string, volNr int, opts ...*client.ListOpts) (client.Volume, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, resName, nodeName, volNr, opts)
	} else {
		tmpRet = _mock.Called(ctx, resName, nodeName, volNr)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetVolume")
	}

	var r0 client.Volume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, ...*client.ListOpts) (client.Volume, error)); ok {
		return returnFunc(ctx, resName, nodeName, volNr, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, ...*client.ListOpts) client.Volume); ok {
		r0 = returnFunc(ctx, resName, nodeName, volNr, opts...)
	} else {
		r0 = ret.Get(0).(client.Volume)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int, ...*client.ListOpts) error); ok {
		r1 = returnFunc(ctx, resName, nodeName, volNr, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceProvider_GetVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVolume'
type ResourceProvider_GetVolume_Call struct {
	*mock.Call
}

// GetVolume is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - nodeName string
//   - volNr int
//   - opts ...*client.ListOpts
func (_e *ResourceProvider_Expecter) GetVolume(ctx any, resName any, nodeName any, volNr any, opts ...any) *ResourceProvider_GetVolume_Call {
	return &ResourceProvider_GetVolume_Call{Call: _e.mock.On("GetVolume",
		append([]any{ctx, resName, nodeName, volNr}, opts...)...)}
}

func (_c *ResourceProvider_GetVolume_Call) Run(run func(ctx context.Context, resName string, nodeName string, volNr int, opts ...*client.ListOpts)) *ResourceProvider_GetVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 []*client.ListOpts
		var variadicArgs []*client.ListOpts
		if len(args) > 4 {
			variadicArgs = args[4].([]*client.ListOpts)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *ResourceProvider_GetVolume_Call) Return(volume client.Volume, err error) *ResourceProvider_GetVolume_Call {
	_c.Call.Return(volume, err)
	return _c
}

func (_c *ResourceProvider_GetVolume_Call) RunAndReturn(run func(ctx context.Context, resName string, nodeName string, volNr int, opts ...*client.ListOpts) (client.Volume, error)) *ResourceProvider_GetVolume_Call {
	_c.Call.Return(run)
	return _c
}

// GetVolumeDefinitionPropsInfos provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) GetVolumeDefinitionPropsInfos(ctx context.Context, resName string, opts ...*client.ListOpts) ([]client.PropsInfo, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, resName, opts)
	} else {
		tmpRet = _mock.Called(ctx, resName)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetVolumeDefinitionPropsInfos")
	}

	var r0 []client.PropsInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*client.ListOpts) ([]client.PropsInfo, error)); ok {
		return returnFunc(ctx, resName, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*client.ListOpts) []client.PropsInfo); ok {
		r0 = returnFunc(ctx, resName, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.PropsInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...*client.ListOpts) error); ok {
		r1 = returnFunc(ctx, resName, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceProvider_GetVolumeDefinitionPropsInfos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVolumeDefinitionPropsInfos'
type ResourceProvider_GetVolumeDefinitionPropsInfos_Call struct {
	*mock.Call
}

// GetVolumeDefinitionPropsInfos is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - opts ...*client.ListOpts
func (_e *ResourceProvider_Expecter) GetVolumeDefinitionPropsInfos(ctx any, resName any, opts ...any) *ResourceProvider_GetVolumeDefinitionPropsInfos_Call {
	return &ResourceProvider_GetVolumeDefinitionPropsInfos_Call{Call: _e.mock.On("GetVolumeDefinitionPropsInfos",
		append([]any{ctx, resName}, opts...)...)}
}

func (_c *ResourceProvider_GetVolumeDefinitionPropsInfos_Call) Run(run func(ctx context.Context, resName string, opts ...*client.ListOpts)) *ResourceProvider_GetVolumeDefinitionPropsInfos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*client.ListOpts
		var variadicArgs []*client.ListOpts
		if len(args) > 2 {
			variadicArgs = args[2].([]*client.ListOpts)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *ResourceProvider_GetVolumeDefinitionPropsInfos_Call) Return(propsInfos []client.PropsInfo, err error) *ResourceProvider_GetVolumeDefinitionPropsInfos_Call {
	_c.Call.Return(propsInfos, err)
	return _c
}

func (_c *ResourceProvider_GetVolumeDefinitionPropsInfos_Call) RunAndReturn(run func(ctx context.Context, resName string, opts ...*client.ListOpts) ([]client.PropsInfo, error)) *ResourceProvider_GetVolumeDefinitionPropsInfos_Call {
	_c.Call.Return(run)
	return _c
}

// GetVolumePropsInfos provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) GetVolumePropsInfos(ctx context.Context, resName string, nodeName string, opts ...*client.ListOpts) ([]client.PropsInfo, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, resName, nodeName, opts)
	} else {
		tmpRet = _mock.Called(ctx, resName, nodeName)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetVolumePropsInfos")
	}

	var r0 []client.PropsInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...*client.ListOpts) ([]client.PropsInfo, error)); ok {
		return returnFunc(ctx, resName, nodeName, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...*client.ListOpts) []client.PropsInfo); ok {
		r0 = returnFunc(ctx, resName, nodeName, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.PropsInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, ...*client.ListOpts) error); ok {
		r1 = returnFunc(ctx, resName, nodeName, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceProvider_GetVolumePropsInfos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVolumePropsInfos'
type ResourceProvider_GetVolumePropsInfos_Call struct {
	*mock.Call
}

// GetVolumePropsInfos is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - nodeName string
//   - opts ...*client.ListOpts
func (_e *ResourceProvider_Expecter) GetVolumePropsInfos(ctx any, resName any, nodeName any, opts ...any) *ResourceProvider_GetVolumePropsInfos_Call {
	return &ResourceProvider_GetVolumePropsInfos_Call{Call: _e.mock.On("GetVolumePropsInfos",
		append([]any{ctx, resName, nodeName}, opts...)...)}
}

func (_c *ResourceProvider_GetVolumePropsInfos_Call) Run(run func(ctx context.Context, resName string, nodeName string, opts ...*client.ListOpts)) *ResourceProvider_GetVolumePropsInfos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []*client.ListOpts
		var variadicArgs []*client.ListOpts
		if len(args) > 3 {
			variadicArgs = args[3].([]*client.ListOpts)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *ResourceProvider_GetVolumePropsInfos_Call) Return(propsInfos []client.PropsInfo, err error) *ResourceProvider_GetVolumePropsInfos_Call {
	_c.Call.Return(propsInfos, err)
	return _c
}

func (_c *ResourceProvider_GetVolumePropsInfos_Call) RunAndReturn(run func(ctx context.Context, resName string, nodeName string, opts ...*client.ListOpts) ([]client.PropsInfo, error)) *ResourceProvider_GetVolumePropsInfos_Call {
	_c.Call.Return(run)
	return _c
}

// GetVolumes provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) GetVolumes(ctx context.Context, resName string, nodeName string, opts ...*client.ListOpts) ([]client.Volume, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, resName, nodeName, opts)
	} else {
		tmpRet = _mock.Called(ctx, resName, nodeName)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetVolumes")
	}

	var r0 []client.Volume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...*client.ListOpts) ([]client.Volume, error)); ok {
		return returnFunc(ctx, resName, nodeName, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...*client.ListOpts) []client.Volume); ok {
		r0 = returnFunc(ctx, resName, nodeName, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.Volume)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, ...*client.ListOpts) error); ok {
		r1 = returnFunc(ctx, resName, nodeName, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceProvider_GetVolumes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVolumes'
type ResourceProvider_GetVolumes_Call struct {
	*mock.Call
}

// GetVolumes is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - nodeName string
//   - opts ...*client.ListOpts
func (_e *ResourceProvider_Expecter) GetVolumes(ctx any, resName any, nodeName any, opts ...any) *ResourceProvider_GetVolumes_Call {
	return &ResourceProvider_GetVolumes_Call{Call: _e.mock.On("GetVolumes",
		append([]any{ctx, resName, nodeName}, opts...)...)}
}

func (_c *ResourceProvider_GetVolumes_Call) Run(run func(ctx context.Context, resName string, nodeName string, opts ...*client.ListOpts)) *ResourceProvider_GetVolumes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []*client.ListOpts
		var variadicArgs []*client.ListOpts
		if len(args) > 3 {
			variadicArgs = args[3].([]*client.ListOpts)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *ResourceProvider_GetVolumes_Call) Return(volumes []client.Volume, err error) *ResourceProvider_GetVolumes_Call {
	_c.Call.Return(volumes, err)
	return _c
}

func (_c *ResourceProvider_GetVolumes_Call) RunAndReturn(run func(ctx context.Context, resName string, nodeName string, opts ...*client.ListOpts) ([]client.Volume, error)) *ResourceProvider_GetVolumes_Call {
	_c.Call.Return(run)
	return _c
}

// MakeAvailable provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) MakeAvailable(ctx context.Context, resName string, nodeName string, makeAvailable client.ResourceMakeAvailable) error {
	ret := _mock.Called(ctx, resName, nodeName, makeAvailable)

	if len(ret) == 0 {
		panic("no return value specified for MakeAvailable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.ResourceMakeAvailable) error); ok {
		r0 = returnFunc(ctx, resName, nodeName, makeAvailable)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceProvider_MakeAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakeAvailable'
type ResourceProvider_MakeAvailable_Call struct {
	*mock.Call
}

// MakeAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - nodeName string
//   - makeAvailable client.ResourceMakeAvailable
func (_e *ResourceProvider_Expecter) MakeAvailable(ctx any, resName any, nodeName any, makeAvailable any) *ResourceProvider_MakeAvailable_Call {
	return &ResourceProvider_MakeAvailable_Call{Call: _e.mock.On("MakeAvailable", ctx, resName, nodeName, makeAvailable)}
}

func (_c *ResourceProvider_MakeAvailable_Call) Run(run func(ctx context.Context, resName string, nodeName string, makeAvailable client.ResourceMakeAvailable)) *ResourceProvider_MakeAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 client.ResourceMakeAvailable
		if args[3] != nil {
			arg3 = args[3].(client.ResourceMakeAvailable)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceProvider_MakeAvailable_Call) Return(err error) *ResourceProvider_MakeAvailable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceProvider_MakeAvailable_Call) RunAndReturn(run func(ctx context.Context, resName string, nodeName string, makeAvailable client.ResourceMakeAvailable) error) *ResourceProvider_MakeAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// Migrate provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) Migrate(ctx context.Context, resName string, fromNodeName string, toNodeName string, storagePoolName string) error {
	ret := _mock.Called(ctx, resName, fromNodeName, toNodeName, storagePoolName)

	if len(ret) == 0 {
		panic("no return value specified for Migrate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, resName, fromNodeName, toNodeName, storagePoolName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceProvider_Migrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migrate'
type ResourceProvider_Migrate_Call struct {
	*mock.Call
}

// Migrate is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - fromNodeName string
//   - toNodeName string
//   - storagePoolName string
func (_e *ResourceProvider_Expecter) Migrate(ctx any, resName any, fromNodeName any, toNodeName any, storagePoolName any) *ResourceProvider_Migrate_Call {
	return &ResourceProvider_Migrate_Call{Call: _e.mock.On("Migrate", ctx, resName, fromNodeName, toNodeName, storagePoolName)}
}

func (_c *ResourceProvider_Migrate_Call) Run(run func(ctx context.Context, resName string, fromNodeName string, toNodeName string, storagePoolName string)) *ResourceProvider_Migrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ResourceProvider_Migrate_Call) Return(err error) *ResourceProvider_Migrate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceProvider_Migrate_Call) RunAndReturn(run func(ctx context.Context, resName string, fromNodeName string, toNodeName string, storagePoolName string) error) *ResourceProvider_Migrate_Call {
	_c.Call.Return(run)
	return _c
}

// Modify provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) Modify(ctx context.Context, resName string, nodeName string, props client.GenericPropsModify) error {
	ret := _mock.Called(ctx, resName, nodeName, props)

	if len(ret) == 0 {
		panic("no return value specified for Modify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.GenericPropsModify) error); ok {
		r0 = returnFunc(ctx, resName, nodeName, props)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceProvider_Modify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modify'
type ResourceProvider_Modify_Call struct {
	*mock.Call
}

// Modify is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - nodeName string
//   - props client.GenericPropsModify
func (_e *ResourceProvider_Expecter) Modify(ctx any, resName any, nodeName any, props any) *ResourceProvider_Modify_Call {
	return &ResourceProvider_Modify_Call{Call: _e.mock.On("Modify", ctx, resName, nodeName, props)}
}

func (_c *ResourceProvider_Modify_Call) Run(run func(ctx context.Context, resName string, nodeName string, props client.GenericPropsModify)) *ResourceProvider_Modify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 client.GenericPropsModify
		if args[3] != nil {
			arg3 = args[3].(client.GenericPropsModify)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceProvider_Modify_Call) Return(err error) *ResourceProvider_Modify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceProvider_Modify_Call) RunAndReturn(run func(ctx context.Context, resName string, nodeName string, props client.GenericPropsModify) error) *ResourceProvider_Modify_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyConnection provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) ModifyConnection(ctx context.Context, resName string, nodeAName string, nodeBName string, props client.GenericPropsModify) error {
	ret := _mock.Called(ctx, resName, nodeAName, nodeBName, props)

	if len(ret) == 0 {
		panic("no return value specified for ModifyConnection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, client.GenericPropsModify) error); ok {
		r0 = returnFunc(ctx, resName, nodeAName, nodeBName, props)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceProvider_ModifyConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyConnection'
type ResourceProvider_ModifyConnection_Call struct {
	*mock.Call
}

// ModifyConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - nodeAName string
//   - nodeBName string
//   - props client.GenericPropsModify
func (_e *ResourceProvider_Expecter) ModifyConnection(ctx any, resName any, nodeAName any, nodeBName any, props any) *ResourceProvider_ModifyConnection_Call {
	return &ResourceProvider_ModifyConnection_Call{Call: _e.mock.On("ModifyConnection", ctx, resName, nodeAName, nodeBName, props)}
}

func (_c *ResourceProvider_ModifyConnection_Call) Run(run func(ctx context.Context, resName string, nodeAName string, nodeBName string, props client.GenericPropsModify)) *ResourceProvider_ModifyConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 client.GenericPropsModify
		if args[4] != nil {
			arg4 = args[4].(client.GenericPropsModify)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ResourceProvider_ModifyConnection_Call) Return(err error) *ResourceProvider_ModifyConnection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceProvider_ModifyConnection_Call) RunAndReturn(run func(ctx context.Context, resName string, nodeAName string, nodeBName string, props client.GenericPropsModify) error) *ResourceProvider_ModifyConnection_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyDRBDProxy provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) ModifyDRBDProxy(ctx context.Context, resName string, props client.DrbdProxyModify) error {
	ret := _mock.Called(ctx, resName, props)

	if len(ret) == 0 {
		panic("no return value specified for ModifyDRBDProxy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.DrbdProxyModify) error); ok {
		r0 = returnFunc(ctx, resName, props)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceProvider_ModifyDRBDProxy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyDRBDProxy'
type ResourceProvider_ModifyDRBDProxy_Call struct {
	*mock.Call
}

// ModifyDRBDProxy is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - props client.DrbdProxyModify
func (_e *ResourceProvider_Expecter) ModifyDRBDProxy(ctx any, resName any, props any) *ResourceProvider_ModifyDRBDProxy_Call {
	return &ResourceProvider_ModifyDRBDProxy_Call{Call: _e.mock.On("ModifyDRBDProxy", ctx, resName, props)}
}

func (_c *ResourceProvider_ModifyDRBDProxy_Call) Run(run func(ctx context.Context, resName string, props client.DrbdProxyModify)) *ResourceProvider_ModifyDRBDProxy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.DrbdProxyModify
		if args[2] != nil {
			arg2 = args[2].(client.DrbdProxyModify)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceProvider_ModifyDRBDProxy_Call) Return(err error) *ResourceProvider_ModifyDRBDProxy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceProvider_ModifyDRBDProxy_Call) RunAndReturn(run func(ctx context.Context, resName string, props client.DrbdProxyModify) error) *ResourceProvider_ModifyDRBDProxy_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyVolume provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) ModifyVolume(ctx context.Context, resName string, nodeName string, volNr int, props client.GenericPropsModify) error {
	ret := _mock.Called(ctx, resName, nodeName, volNr, props)

	if len(ret) == 0 {
		panic("no return value specified for ModifyVolume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, client.GenericPropsModify) error); ok {
		r0 = returnFunc(ctx, resName, nodeName, volNr, props)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceProvider_ModifyVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyVolume'
type ResourceProvider_ModifyVolume_Call struct {
	*mock.Call
}

// ModifyVolume is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - nodeName string
//   - volNr int
//   - props client.GenericPropsModify
func (_e *ResourceProvider_Expecter) ModifyVolume(ctx any, resName any, nodeName any, volNr any, props any) *ResourceProvider_ModifyVolume_Call {
	return &ResourceProvider_ModifyVolume_Call{Call: _e.mock.On("ModifyVolume", ctx, resName, nodeName, volNr, props)}
}

func (_c *ResourceProvider_ModifyVolume_Call) Run(run func(ctx context.Context, resName string, nodeName string, volNr int, props client.GenericPropsModify)) *ResourceProvider_ModifyVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 client.GenericPropsModify
		if args[4] != nil {
			arg4 = args[4].(client.GenericPropsModify)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ResourceProvider_ModifyVolume_Call) Return(err error) *ResourceProvider_ModifyVolume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceProvider_ModifyVolume_Call) RunAndReturn(run func(ctx context.Context, resName string, nodeName string, volNr int, props client.GenericPropsModify) error) *ResourceProvider_ModifyVolume_Call {
	_c.Call.Return(run)
	return _c
}

// QueryMaxVolumeSize provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) QueryMaxVolumeSize(ctx context.Context, filter client.AutoSelectFilter) (client.MaxVolumeSizes, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for QueryMaxVolumeSize")
	}

	var r0 client.MaxVolumeSizes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.AutoSelectFilter) (client.MaxVolumeSizes, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.AutoSelectFilter) client.MaxVolumeSizes); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		r0 = ret.Get(0).(client.MaxVolumeSizes)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.AutoSelectFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceProvider_QueryMaxVolumeSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryMaxVolumeSize'
type ResourceProvider_QueryMaxVolumeSize_Call struct {
	*mock.Call
}

// QueryMaxVolumeSize is a helper method to define mock.On call
//   - ctx context.Context
//   - filter client.AutoSelectFilter
func (_e *ResourceProvider_Expecter) QueryMaxVolumeSize(ctx any, filter any) *ResourceProvider_QueryMaxVolumeSize_Call {
	return &ResourceProvider_QueryMaxVolumeSize_Call{Call: _e.mock.On("QueryMaxVolumeSize", ctx, filter)}
}

func (_c *ResourceProvider_QueryMaxVolumeSize_Call) Run(run func(ctx context.Context, filter client.AutoSelectFilter)) *ResourceProvider_QueryMaxVolumeSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.AutoSelectFilter
		if args[1] != nil {
			arg1 = args[1].(client.AutoSelectFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResourceProvider_QueryMaxVolumeSize_Call) Return(maxVolumeSizes client.MaxVolumeSizes, err error) *ResourceProvider_QueryMaxVolumeSize_Call {
	_c.Call.Return(maxVolumeSizes, err)
	return _c
}

func (_c *ResourceProvider_QueryMaxVolumeSize_Call) RunAndReturn(run func(ctx context.Context, filter client.AutoSelectFilter) (client.MaxVolumeSizes, error)) *ResourceProvider_QueryMaxVolumeSize_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreSnapshot provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) RestoreSnapshot(ctx context.Context, origResName string, snapName string, snapRestoreConf client.SnapshotRestore) error {
	ret := _mock.Called(ctx, origResName, snapName, snapRestoreConf)

	if len(ret) == 0 {
		panic("no return value specified for RestoreSnapshot")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.SnapshotRestore) error); ok {
		r0 = returnFunc(ctx, origResName, snapName, snapRestoreConf)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceProvider_RestoreSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreSnapshot'
type ResourceProvider_RestoreSnapshot_Call struct {
	*mock.Call
}

// RestoreSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - origResName string
//   - snapName string
//   - snapRestoreConf client.SnapshotRestore
func (_e *ResourceProvider_Expecter) RestoreSnapshot(ctx any, origResName any, snapName any, snapRestoreConf any) *ResourceProvider_RestoreSnapshot_Call {
	return &ResourceProvider_RestoreSnapshot_Call{Call: _e.mock.On("RestoreSnapshot", ctx, origResName, snapName, snapRestoreConf)}
}

func (_c *ResourceProvider_RestoreSnapshot_Call) Run(run func(ctx context.Context, origResName string, snapName string, snapRestoreConf client.SnapshotRestore)) *ResourceProvider_RestoreSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 client.SnapshotRestore
		if args[3] != nil {
			arg3 = args[3].(client.SnapshotRestore)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceProvider_RestoreSnapshot_Call) Return(err error) *ResourceProvider_RestoreSnapshot_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceProvider_RestoreSnapshot_Call) RunAndReturn(run func(ctx context.Context, origResName string, snapName string, snapRestoreConf client.SnapshotRestore) error) *ResourceProvider_RestoreSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreVolumeDefinitionSnapshot provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) RestoreVolumeDefinitionSnapshot(ctx context.Context, origResName string, snapName string, snapRestoreConf client.SnapshotRestore) error {
	ret := _mock.Called(ctx, origResName, snapName, snapRestoreConf)

	if len(ret) == 0 {
		panic("no return value specified for RestoreVolumeDefinitionSnapshot")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.SnapshotRestore) error); ok {
		r0 = returnFunc(ctx, origResName, snapName, snapRestoreConf)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceProvider_RestoreVolumeDefinitionSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreVolumeDefinitionSnapshot'
type ResourceProvider_RestoreVolumeDefinitionSnapshot_Call struct {
	*mock.Call
}

// RestoreVolumeDefinitionSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - origResName string
//   - snapName string
//   - snapRestoreConf client.SnapshotRestore
func (_e *ResourceProvider_Expecter) RestoreVolumeDefinitionSnapshot(ctx any, origResName any, snapName any, snapRestoreConf any) *ResourceProvider_RestoreVolumeDefinitionSnapshot_Call {
	return &ResourceProvider_RestoreVolumeDefinitionSnapshot_Call{Call: _e.mock.On("RestoreVolumeDefinitionSnapshot", ctx, origResName, snapName, snapRestoreConf)}
}

func (_c *ResourceProvider_RestoreVolumeDefinitionSnapshot_Call) Run(run func(ctx context.Context, origResName string, snapName string, snapRestoreConf client.SnapshotRestore)) *ResourceProvider_RestoreVolumeDefinitionSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 client.SnapshotRestore
		if args[3] != nil {
			arg3 = args[3].(client.SnapshotRestore)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceProvider_RestoreVolumeDefinitionSnapshot_Call) Return(err error) *ResourceProvider_RestoreVolumeDefinitionSnapshot_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceProvider_RestoreVolumeDefinitionSnapshot_Call) RunAndReturn(run func(ctx context.Context, origResName string, snapName string, snapRestoreConf client.SnapshotRestore) error) *ResourceProvider_RestoreVolumeDefinitionSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// RollbackSnapshot provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) RollbackSnapshot(ctx context.Context, resName string, snapName string) error {
	ret := _mock.Called(ctx, resName, snapName)

	if len(ret) == 0 {
		panic("no return value specified for RollbackSnapshot")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, resName, snapName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceProvider_RollbackSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollbackSnapshot'
type ResourceProvider_RollbackSnapshot_Call struct {
	*mock.Call
}

// RollbackSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - snapName string
func (_e *ResourceProvider_Expecter) RollbackSnapshot(ctx any, resName any, snapName any) *ResourceProvider_RollbackSnapshot_Call {
	return &ResourceProvider_RollbackSnapshot_Call{Call: _e.mock.On("RollbackSnapshot", ctx, resName, snapName)}
}

func (_c *ResourceProvider_RollbackSnapshot_Call) Run(run func(ctx context.Context, resName string, snapName string)) *ResourceProvider_RollbackSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceProvider_RollbackSnapshot_Call) Return(err error) *ResourceProvider_RollbackSnapshot_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceProvider_RollbackSnapshot_Call) RunAndReturn(run func(ctx context.Context, resName string, snapName string) error) *ResourceProvider_RollbackSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// UnmakeAvailable provides a mock function for the type ResourceProvider
func (_mock *ResourceProvider) UnmakeAvailable(ctx context.Context, resName string, nodeName string) error {
	ret := _mock.Called(ctx, resName, nodeName)

	if len(ret) == 0 {
		panic("no return value specified for UnmakeAvailable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, resName, nodeName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceProvider_UnmakeAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnmakeAvailable'
type ResourceProvider_UnmakeAvailable_Call struct {
	*mock.Call
}

// UnmakeAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - resName string
//   - nodeName string
func (_e *ResourceProvider_Expecter) UnmakeAvailable(ctx any, resName any, nodeName any) *ResourceProvider_UnmakeAvailable_Call {
	return &ResourceProvider_UnmakeAvailable_Call{Call: _e.mock.On("UnmakeAvailable", ctx, resName, nodeName)}
}

func (_c *ResourceProvider_UnmakeAvailable_Call) Run(run func(ctx context.Context, resName string, nodeName string)) *ResourceProvider_UnmakeAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceProvider_UnmakeAvailable_Call) Return(err error) *ResourceProvider_UnmakeAvailable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceProvider_UnmakeAvailable_Call) RunAndReturn(run func(ctx context.Context, resName string, nodeName string) error) *ResourceProvider_UnmakeAvailable_Call {
	_c.Call.Return(run)
	return _c
}
