name: build
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build:
    name: Build piraeus-csi
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up cosign
        if: ${{ github.event_name != 'pull_request' }}
        uses: sigstore/cosign-installer@v3
      - name: login to registry
        if: github.event_name != 'pull_request'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login --username=${DOCKER_USERNAME} --password-stdin quay.io <<< "${DOCKER_PASSWORD}"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
          tags: |
            type=sha
            type=ref,event=tag
            type=ref,event=pr
      - name: Set VERSION
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build
        uses: docker/bake-action@v6
        id: bake
        with:
          provenance: true
          sbom: true
          push: ${{ github.event_name != 'pull_request' }}
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file }}
      - name: Sign images
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          jq '.[] | select(type=="object") | select(."containerimage.digest") | ."containerimage.digest" as $DIGEST | ."image.name" | split(":")[0] | "\(.)@\($DIGEST)"' -r <<<'${{ steps.bake.outputs.metadata }}' \
            | xargs --no-run-if-empty cosign sign --yes
